function  [kde1, input_data] = projectKDEandDataToSubspace(kde1, input_data, minvalue, all_layers )

output = subspacePrewhitenTransform( 'pdf', kde1.pdf, 'minEigenEnergy',minvalue, ...
                'globalCov', kde1.ikdeParams.scale.Cov,...
                'transDirection', 'forward',...
                'allLayers', all_layers, 'additional_data', input_data ) ;
kde1.pdf =  output.pdf ;          
input_data = output.additional_data ;