Description of phy_Object
phy_Object
PURPOSE
SYNOPSIS
This is a script file.
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
phy_Object
This function is called by:
phy_Object
phy_Tobject
phy_makeTObject refresh the link(the pointers) between the image cells and the Tobjects
phy_segmentBudneck segment budneck function
phy_segmentCellsBallon find cell center based on phase image using bwdist to detect cell centers and
phy_segmentCellsOmothetie segmentation funtion of cells by omothetie
phy_segmentCellsWatershed segment cells with watershed method
phy_segmentCellsWatershedForme segment cells with watershed method
phy_segmentCellsWatershedFormeBF segment cells with watershed method
phy_struct2class change from cells in struct format to cells in class format
phyloCell_mainGUI Main graphical user interface;
start start the main program
SUBFUNCTIONS
function c = phy_Object(N,X,Y)
function depData = get.dependentData(obj)
function a = get.area(obj)
SOURCE CODE
classdef phy_Object < handle %inherit handle because otherwhise the values of private can not be changed by ordinary methods
    properties
        n=0;
        x=[];
        y=[];
        area=0;
        ox=0;
        oy=0;
        image=0; %image of presence
        mother=0;
        daughterList=[];
        divisionTimes=[];
        budTimes=[];
        Mean=0;
        Max=0;
        Min=0;
        Median=0;
        Nrpoints=0;
        Mean_cell=0;
        htext=[];
        hcontour=[];
        move=0;
        dist_min=0;
        cell1=[]; %cells1 of contact;
        cell2=[];%cells2 of contact;
        selected=false;
        dependentData=0;
        meanLevelsInside=0;
    end
    properties (Dependent = true)
    end
    methods
        %constructor
        function c = phy_Object(N,X,Y)
            if nargin > 0
                c.n = N;
                c.x = X;
                c.y = Y;
            end
        end % phy_Object
%         function delete(obj)
%             obj.n=0;
%             if ishandle(obj.hcontour)&(obj.hcontour~=0)
%                 delete(obj.hcontour);
%             end
%         end
        function depData = get.dependentData(obj)
            depData = obj.area;
        end
        function a = get.area(obj)
            if obj.area==0
                obj.area= polyarea(obj.x,obj.y);
                a=obj.area;
            else
                a=obj.area;
            end
        end
%         function a = get.ox(obj)
%             if obj.ox==0
%                 obj.ox= mean(obj.x);
%                 a=obj.ox;
%             else
%                 a=obj.ox;
%             end
%         end
    end
end