Description of phy_getCellCenter
phy_getCellCenter
PURPOSE
get the center of the cells
SYNOPSIS
function [a b]=phy_getCellCenter(x,y)
DESCRIPTION
get the center of the cells
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
phy_ballModel ball model is a further evolution of ball that lets one relax many cells
phy_createCellsComplex
phy_segmentCellsBallon find cell center based on phase image using bwdist to detect cell centers and
phy_selfAvoding separates the overlapping cells (from ball model)
SOURCE CODE
%get the center of the cells
function [a b]=phy_getCellCenter(x,y)
if (numel(x)>1 && numel(y)>1)
    n=numel(x);
    a= sum(x(1:n-1))/(n-1);
    b= sum(y(1:n-1))/(n-1);
else
   a=0;
   b=0;
end