Description of phy_findCellCenters
phy_findCellCenters
PURPOSE
replace the previous findCellCenter function : about 8 faster !
SYNOPSIS
function [listx2 listy2 distance imdistance2]=phy_findCellCenters(imdata,display,cellcelldistance)
DESCRIPTION
 replace the previous findCellCenter function : about 8 faster !
 find cell centers based on distance to edges.
 display=1 shows the result as a figure;
display=1;
CROSS-REFERENCE INFORMATION
This function calls:
phy_localMaximum calculate the local maximus (equivalent to imregionalmax function but with respect of distance between points)
phy_scale SCALE Scales matrix elements to a new range.
This function is called by:
phy_segmentCellsBallon find cell center based on phase image using bwdist to detect cell centers and
phy_segmentCellsOmothetie segmentation funtion of cells by omothetie
phy_segmentCellsWatershed segment cells with watershed method
phy_segmentCellsWatershedForme segment cells with watershed method
phy_segmentCellsWatershedFormeBF segment cells with watershed method
SOURCE CODE
function [listx2 listy2 distance imdistance2]=phy_findCellCenters(imdata,display,cellcelldistance)
% replace the previous findCellCenter function : about 8 faster !
% find cell centers based on distance to edges.
% display=1 shows the result as a figure;
%display=1;
imdata=phy_scale(imdata);
sizemin=cellcelldistance/20; % minimal distance to edge to be considered, roughly the min cell radius , pixel units
sizemax=cellcelldistance*1.5; % maximal distance to edge that is tolerable
%cellcelldistance=15; % drough distance between cells
thresh=0.5:-0.05:0.05; % thresholding applied to generate BW image
%find the right threshold to detect the contour of the colonie
maxe=max(max(imdata));
meane=mean2(imdata);
[counts,x]=imhist(imdata);
count2=filter(ones(1,1),1,counts);
d=diff(count2);
d2=filter(ones(1,1),1,d);
if display
    figure;plot(x(1:end-1),d2);
end
[minv minind]=min(d2);
meanv=mean(d2);
ind=find(d2>meanv+minv);
final_ind=find(ind>minind,1,'first');
x(ind(final_ind));% the value of threshold
imbw=round(double(im2bw(imdata,x(ind(final_ind))+0.05))); %threshold+0.05
if display
    figure;imshow(imbw);
end
se = strel('disk',round(cellcelldistance/2));
imbw=imclose(imbw,se);
imbw=imfill(imbw,'holes');
%figure;imshow(imbw);
%tic;imbw = bwmorph(imbw,'fill');toc
se = strel('disk',3);
imbw=imopen(imbw,se);
imbw=bwareaopen(imbw,round(cellcelldistance^2*pi/2),4);
C=~imbw;
C=imdilate(C,strel('disk',round(cellcelldistance/8)));
if display
    figure; imshow(double(C)+imdata);
    % figure; imshow(double(C2)+imdata);
end
%----------------------------------
%C=0;
imbwtot=zeros(size(imdata));
imdistance=zeros(size(imdata));
immeandist=zeros(size(imdata));
imcount=zeros(size(imdata));
imdistance2=zeros(size(imdata));
%img2=imdata+NG;
for it=thresh
    % imbw=im2bw(imdata,double(meane+it*(maxe-meane))/65536);
    imbw=im2bw(imdata,double(meane+it*(maxe-meane)));
    %imbwNG=im2bw(NG,double(meanNG+it*(maxNG-meanNG)));
    imdist=bwdist(imbw|C);
    imdistance2=imdistance2+imdist;
end
imdistance2=imdistance2/numel(thresh);
imdistance2(C)=0;
pix=phy_localMaximum(imdistance2,cellcelldistance);
temp2=zeros(size(imdata));
temp2(pix)=1;
se = strel('disk',1);
%temp3 = imdilate(imdistance2,se);
temp3=imdilate(temp2,se);
temp3=bwlabel(temp3);
%figure, imshow(temp3+imdata);
s  = regionprops(temp3, imdistance2, 'Centroid','MeanIntensity');
centroids = cat(1, s.Centroid);
meanInt=cat(1,s.MeanIntensity);
listx2=[];
listy2=[];
distance=[];
%distance2=uint8([]);
for i=1:length(centroids(:,1))
    x=centroids(i,1);
    y=centroids(i,2);
    dist=imdistance2(round(y),round(x));
    %dist2=meanInt(i);
    if dist<sizemin
        continue;
    end
    if dist>sizemax
        continue;
    end
    if x<20
        continue;
    end
    if y<20
        continue;
    end
    if y>size(imdata,1)-20
        continue;
    end
    if x>size(imdata,2)-20
        continue;
    end
    distance=[distance double(dist) ];
    % distance2=[distance2 uint8(round(dist2))];
    listx2=[listx2 x];
    listy2=[listy2 y];
end
if nargin>=2
    if display==1
        %   figure, imshow(temp3,[]); hold on ;
        %   line(listx2,listy2,'Marker','o','LineStyle','none');
        figure, imshow(imdata,[]);
        hold on; line(listx2,listy2,'Marker','o','LineStyle','none','Color','r');
        for i=1:numel(listx2)
            text(listx2(i),listy2(i)-2,num2str(round(distance(i))),'Color','r');
        end
    end
end