Description of phy_makeTObject
phy_makeTObject
PURPOSE
refresh the link(the pointers) between the image cells and the Tobjects
SYNOPSIS
function [tObjectOut fChanged]=phy_makeTObject(objects,tObjectIn)
DESCRIPTION
refresh the link(the pointers) between the image cells and the Tobjects
CROSS-REFERENCE INFORMATION
This function calls:
phy_Object
phy_Tobject
This function is called by:
phyloCell_mainGUI Main graphical user interface;
SOURCE CODE
%refresh the link(the pointers) between the image cells and the Tobjects
function [tObjectOut fChanged]=phy_makeTObject(objects,tObjectIn)
fChanged=[];
if nargin==2
    tObjectOut=tObjectIn;
    for i=1:length(tObjectIn)
        tObjectOut(i).Obj=phy_Object;
    end
else
    tObjectOut=phy_Tobject;
end
for i=1:numel(objects)
    n=objects(i).n;
    if n~=0 && objects(i).ox~=0
        if n>length(tObjectOut)
            tObjectOut(n)=phy_Tobject;
        end
        tObjectOut(n).addObject(objects(i));
    end
    if n~=0 && objects(i).ox==0 %if the object was deleted, delete his number
        objects(i).n=0;
    end
end
for i=1:numel(tObjectOut)
    if length(tObjectOut(i).Obj)==1 && tObjectOut(i).Obj.ox==0
        tObjectOut(i)=phy_Tobject;
    end
end