Description of phyloCell_mainGUI
phyloCell_mainGUI
PURPOSE
Main graphical user interface;
SYNOPSIS
function varargout = phyloCell_mainGUI(varargin)
DESCRIPTION
Main graphical user interface;
Bild the main figure and all the grafics on that figure;
Call all the algorithms.
CROSS-REFERENCE INFORMATION
This function calls:
phy_Object
phy_Tobject
phy_cell2csv Writes cell array content into a *.csv file.
phy_createTimeLapseProjectGui create time lapse project from images
phy_inputsdlg INPUTSDLG Enhanced input dialog box supporting multiple data types
phy_loadTimeLapseImage toa an image from a project
phy_makeTObject refresh the link(the pointers) between the image cells and the Tobjects
phy_mapObjects mapping objects
phy_openProjectGui manage already oppened projects;
phy_plotPedigree this function plots the pedigree in a separate figure
phy_progressbar this m-file modified by Quan Quach on 12/12/07
phy_scale SCALE Scales matrix elements to a new range.
phy_segmentBudneck segment budneck function
phy_segmentCellsBallon find cell center based on phase image using bwdist to detect cell centers and
phy_segmentCellsOmothetie segmentation funtion of cells by omothetie
phy_segmentCellsWatershedForme segment cells with watershed method
phy_segmentCellsWatershedFormeBF segment cells with watershed method
phy_setColorsGui set the colors of the displayed channels
phy_setMothers Based on the geometrical overlap of budnecks and cells, this function
phy_setMothersWithoutBudneck
phy_showObject show the contours of the objects on an image
phy_showPedigree shows pedigree on the figure(lines between the cells)
phy_struct2class change from cells in struct format to cells in class format
This function is called by:
start start the main program
SUBFUNCTIONS
function phyloCell_mainGUI_OpeningFcn(hObject, eventdata, handles, varargin)
function varargout = phyloCell_mainGUI_OutputFcn(hObject, eventdata, handles)
function pushbutton_First1_Callback(hObject, eventdata, handles)
function pushbutton_Previous1_Callback(hObject, eventdata, handles)
function pushbutton_Next1_Callback(hObject, eventdata, handles)
function pushbutton_Last1_Callback(hObject, eventdata, handles)
function pushbutton_Play_Callback(hObject, eventdata, handles)
function pushbutton_segImg_Callback(hObject, eventdata, handles)
function pushbutton_segAll_Callback(hObject, eventdata, handles)
function pushbutton_saveAll_Callback(hObject, eventdata, handles)
function pushbutton_Set_Mother_Callback(hObject, eventdata, handles)
function pushbutton_Set_Number_Callback(hObject, eventdata, handles)
function pushbutton_Delete_Object_Callback(hObject, eventdata, handles)
function pushbutton_Edit_Contour_Callback(hObject, eventdata, handles)
function pushbutton_Create_Object_Callback(hObject, eventdata, handles)
function pushbutton_Clear_Image_Callback(hObject, eventdata, handles)
function pushbutton_Clear_All_Callback(hObject, eventdata, handles)
function slider1_Callback(hObject, eventdata, handles)
function slider1_ButtonDownFcn(hObject, eventdata, handles)
function slider1_CreateFcn(hObject, eventdata, handles)
function slider1_KeyPressFcn(hObject, eventdata, handles)
function editFrame1_Callback(hObject, eventdata, handles)
function edit_Find_Cell_Callback(hObject, eventdata, handles)
function edit_Find_Budneck_Callback(hObject, eventdata, handles)
function edit_Find_Budneck_CreateFcn(hObject, eventdata, handles)
function editFrame1_CreateFcn(hObject, eventdata, handles)
function edit_Find_Cell_CreateFcn(hObject, eventdata, handles)
function edit_TCell_Properties_CreateFcn(hObject, eventdata, handles)
function edit_Cell_Properties_CreateFcn(hObject, eventdata, handles)
function edit_Channel_Poperties_Callback(hObject, eventdata, handles)
function edit_Channel_Poperties_CreateFcn(hObject, eventdata, handles)
function listbox_Channels_Callback(hObject, eventdata, handles)
function listbox_Channels_CreateFcn(hObject, eventdata, handles)
function File_Callback(hObject, eventdata, handles)
function File_Open_TimeLapse_Project_Callback(hObject, eventdata, handles)
function Create_Project_From_Images_Callback(hObject, eventdata, handles)
function Segmentation_Callback(hObject, eventdata, handles)
function Segmentation_SegmentCells_Callback(hObject, eventdata, handles)
function Segmentation_MapCell_Callback(hObject, eventdata, handles)
function Segmentation_SegmentBudneck_Callback(hObject, eventdata, handles)
function Segmentation_MapBudneck_Callback(hObject, eventdata, handles)
function Segmentation_Setings_Callback(hObject, eventdata, handles)
function Pedigree_Callback(hObject, eventdata, handles)
function Pedigree_MakeP_Callback(hObject, eventdata, handles)
function Pedigree_Plot_Pedigree_Callback(hObject, eventdata, handles)
function Pedigree_Setings_Callback(hObject, eventdata, handles)
function Pedigree_Clear_Mothers_Callback(hObject, eventdata, handles)
function View_Callback(hObject, eventdata, handles)
function View_Edit_Cell_Properties_Callback(hObject, eventdata, handles)
function View_Edit_TCell_Properties_Callback(hObject, eventdata, handles)
function View_Set_Channels_Colors_Callback(hObject, eventdata, handles)
function Check_Callback(hObject, eventdata, handles)
function Check_Cells_Callback(hObject, eventdata, handles)
function Check_Budnecks_Callback(hObject, eventdata, handles)
function Export_Data_To_File_Callback(hObject, eventdata, handles)
function Export_frame_to_image_Callback(hObject, eventdata, handles)
function Export_frames_to_movie_Callback(hObject, eventdata, handles)
function OpenProject_ClickedCallback(hObject, eventdata, handles)
function NewProject_ClickedCallback(hObject, eventdata, handles)
function handles=checkbox_ShowCells_Callback(hObject, eventdata, handles)
function handles=checkbox_ShowBudneck_Callback(hObject, eventdata, handles)
function handles=checkbox_ShowCells2_Callback(hObject, eventdata, handles)
function handles=checkbox_Show_Pedigree_Callback(hObject, eventdata, handles)
function Change_Disp1(pos,handles)
function mouseFcn(hObject, eventdata, handles)
function checkBoxChannel_first(hObject, eventdata, handles)
function editChannel_first(hObject, eventdata, handles)
function mousePedigreePlot(hObject, eventdata, handles,haxe)
function mouseAxesImage(hObject, eventdata, handles)
function mouseSelectObject(hObject, eventdata, handles)
function mouse_dragginObj(hObect,evendata,obj)
function status(str,handles)
function figure1_WindowKeyPressFcn(hObject, eventdata, handles)
function figure1_WindowButtonUpFcn(hObject, eventdata, handles)
function Set_Key_Callback(hObject, eventdata, handles)
function Context_Objects_Edit_Contour_Callback(hObject, eventdata, handles)
function Context_Objects_Callback(hObject, eventdata, handles)
function Context_Objects_Set_Number_Callback(hObject, eventdata, handles)
function Context_Objects_Delete_Callback(hObject, eventdata, handles)
function Context_Objects_Copy_Callback(hObject, eventdata, handles)
function Context_Objects_Move_Callback(hObject, eventdata, handles)
function Context_Objects_Lock_Callback(hObject, eventdata, handles)
function Context_Objects_Set_Mother_Callback(hObject, eventdata, handles)
function Context_Objects_Copy_Next_Frame_Callback(hObject, eventdata, handles)
function Context_Image_Paste_Callback(hObject, eventdata, handles)
function Context_Image_Callback(hObject, eventdata, handles)
function Context_Image_Paste_Images_Callback(hObject, eventdata, handles)
function Check_Setings_Callback(hObject, eventdata, handles)
function checkbox_Use_Display_Image_Callback(hObject, eventdata, handles)
function checkbox_Use_Cropped_Image_Callback(hObject, eventdata, handles)
function Analyse_Callback(hObject, eventdata, handles)
function Analyse_Levels_Inside_Contours_Callback(hObject, eventdata, handles)
function Analyse_Plot_Levels_Callback(hObject, eventdata, handles)
function mouseFluoPlot(hObject, eventdata, ha)
SOURCE CODE
%Main graphical user interface;
%Bild the main figure and all the grafics on that figure;
%Call all the algorithms.
function varargout = phyloCell_mainGUI(varargin)
% Begin initialization code - DO NOT EDIT
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
    'gui_Singleton',  gui_Singleton, ...
    'gui_OpeningFcn', @phyloCell_mainGUI_OpeningFcn, ...
    'gui_OutputFcn',  @phyloCell_mainGUI_OutputFcn, ...
    'gui_LayoutFcn',  [] , ...
    'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end
if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end
% End initialization code - DO NOT EDIT
% --- Executes just before phyloCell_mainGUI is made visible.
function phyloCell_mainGUI_OpeningFcn(hObject, eventdata, handles, varargin)
% This function has no output args, see OutputFcn.
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% varargin   command line arguments to phyloCell_mainGUI (see VARARGIN)
global segmentation;
%Open projects is empty when a new widow is oppen
handles.openedProjects={};
%The folder of export is set to current folder
handles.exportDir=pwd;
%initialize with empty cells the shorcut keys
segmentation.shorcutKeys=cell(1,2);
cla(handles.axes1);
%set the current folder to the function folder
spath=which('phyloCell_mainGUI.m');
[pathstr, name, ext, versn] = fileparts(spath);
cd(pathstr);
%copy watershed mayer function to curent directory
if exist('watershed_meyer','file')~=3
    watPath=fullfile(matlabroot, 'toolbox/images/images/private/watershed_meyer.*');
    copyfile(watPath,pwd,'f');
end
addpath CppFiles
if exist('phy_WatershedForme','file')~=3
    mex('CppFiles/phy_WatershedForme.cpp')
end
segmentation.play=false;
segmentation.frame1=1;
%for the same zoom and pan in the next images;
handles.Zoom = zoom;
set(handles.Zoom,'ActionPostCallback',{@mouseFcn,handles});
handles.Pan = pan;
set(handles.Pan,'ActionPostCallback',{@mouseFcn,handles});
% Choose default command line output for phyloCell_mainGUI
handles.output = hObject;
set(handles.slider1,'Value',1);
set(handles.editFrame1, 'String', '1');
% Update handles structure
guidata(hObject, handles);
% --- Outputs from this function are returned to the command line.
function varargout = phyloCell_mainGUI_OutputFcn(hObject, eventdata, handles)
varargout{1} = handles.output;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%% PUSHBUTTON CALLBACK FUNCTIONS %%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% --- Executes on button press in pushbutton_First1.
function pushbutton_First1_Callback(hObject, eventdata, handles)
Min=get(handles.slider1,'Min');
Change_Disp1(Min,handles);
% --- Executes on button press in pushbutton_Previous1.
function pushbutton_Previous1_Callback(hObject, eventdata, handles)
global segmentation;
pos=segmentation.frame1-1;
Change_Disp1(pos,handles);
% --- Executes on button press in pushbutton_Next1.
function pushbutton_Next1_Callback(hObject, eventdata, handles)
global segmentation;
pos=segmentation.frame1+1;
Change_Disp1(pos,handles);
% --- Executes on button press in pushbutton_Last1.
function pushbutton_Last1_Callback(hObject, eventdata, handles)
Max=get(handles.slider1,'Max');
Change_Disp1(Max,handles);
% --- Executes on button press in pushbutton_Play.
function pushbutton_Play_Callback(hObject, eventdata, handles)
global segmentation;
if ~segmentation.play
    segmentation.play=true;
    set(hObject,'String','Pause');
    for i=segmentation.frame1:get(handles.slider1,'Max') % from actual frame to the end
        Change_Disp1(i,handles);  %refresh actual frame
        pause(0.2)
        %if a second click on the button-exit the for loop;
        if ~segmentation.play
            break
        end
    end
else
    %second click change buton and the variable
    segmentation.play=false;
    set(hObject,'String','Play');
end
% the end of the loop rechange the button as before
segmentation.play=false;
set(hObject,'String','Play');
% --- Executes on button press in pushbutton_segImg.
function pushbutton_segImg_Callback(hObject, eventdata, handles)
global segmentation
%budneck=phy_Object;
budnecks=segmentation.budnecks;
cells1=segmentation.cells1;
% cells2=segmentation.cells2;
        ax=floor(segmentation.v_axe1);
if get(handles.checkbox_segBud,'Value')&&(segmentation.budneckChannel~=0) %if check box and if a valid budneckchannel
    if ~(~(get(hObject,'Value'))&&(segmentation.budnecksSegmented(segmentation.frame1)))% execut always if buton pressed but not if already segmented
        budnecks(segmentation.frame1,:)=phy_Object;
        status(['segment frame ',num2str(segmentation.frame1),': budnecks'],handles);
        budneck=phy_segmentBudneck(segmentation.segmentationImage(:,:,segmentation.budneckChannel),segmentation.parametres);
        for j=1:length(budneck)
            budneck(j).image=segmentation.frame1;
            if get(handles.checkbox_Use_Cropped_Image,'value')
                budneck(j).x=budneck(j).x+ax(1)-1;
                budneck(j).y=budneck(j).y+ax(3)-1;
                budneck(j).ox=budneck(j).ox+ax(1)-1;
                budneck(j).oy=budneck(j).oy+ax(3)-1;
            end
            budnecks(segmentation.frame1,j)=budneck(j);
        end
        segmentation.frameChanged(segmentation.frame1)=1;
        segmentation.budnecksSegmented(segmentation.frame1)=1;
        if length(budneck)==1 && budneck.n==0
            segmentation.budnecksSegmented(segmentation.frame1)=0;
        end
    end
    if ishandle(segmentation.myHandles.showBudnecks)
        delete(segmentation.myHandles.showBudnecks);
        delete(segmentation.myHandles.showBudnecksText);
    end
    [segmentation.myHandles.showBudnecks segmentation.myHandles.showBudnecksText]=phy_showObject(handles.axes1,budnecks(segmentation.frame1,:),'b','budnecks',segmentation.myHandles.showBudnecks,segmentation.myHandles.showBudnecksText,'on');
    set(segmentation.myHandles.showBudnecks(:),'ButtonDownFcn',{@mouseSelectObject,handles});
    set(segmentation.myHandles.showBudnecks(:),'UIContextMenu',handles.Context_Objects);
    segmentation.frameChanged(segmentation.frame1)=1;
    segmentation.budnecksMapped(segmentation.frame1)=0;
end
segmentation.budnecks=budnecks;
if get(handles.checkbox_segCells,'Value')&&(segmentation.phaseChannel~=0)
    if ~(~(get(hObject,'Value'))&&(segmentation.cells1Segmented(segmentation.frame1)))% execut always if buton pressed but not if already segmented
%         cells2(segmentation.frame1,:)=phy_Object;
        cells1(segmentation.frame1,:)=phy_Object;
        status(['segment frame ',num2str(segmentation.frame1),': cells'],handles);
        switch segmentation.parametres.segmentation
            case 1
                cells_struct=phy_segmentCellsBallon(segmentation.segmentationImage(:,:,segmentation.phaseChannel),[],'ROI',[],segmentation.parametres);
                cell=phy_struct2class(cells_struct);
                for l=1:length(cell)
                    cell(l).image=segmentation.frame1;
                    if get(handles.checkbox_Use_Cropped_Image,'value')
                        cell(l).x=cell(l).x+ax(1)-1;
                        cell(l).y=cell(l).y+ax(3)-1;
                        cell(l).ox=cell(l).ox+ax(1)-1;
                        cell(l).oy=cell(l).oy+ax(3)-1;
                    end
                    cells1(segmentation.frame1,l)=cell(l);
                end
            case 2
                cell=phy_segmentCellsWatershedForme(segmentation.segmentationImage(:,:,segmentation.phaseChannel),segmentation.parametres);
                for l=1:length(cell)
                    cell(l).image=segmentation.frame1;
                    if get(handles.checkbox_Use_Cropped_Image,'value')
                        cell(l).x=cell(l).x+ax(1)-1;
                        cell(l).y=cell(l).y+ax(3)-1;
                        cell(l).ox=cell(l).ox+ax(1)-1;
                        cell(l).oy=cell(l).oy+ax(3)-1;
                    end
                    cells1(segmentation.frame1,l)=cell(l);
                end
            case 3
                cell=phy_segmentCellsOmothetie(segmentation.segmentationImage(:,:,segmentation.phaseChannel),segmentation.parametres,0);
                for l=1:length(cell)
                    cell(l).image=segmentation.frame1;
                    if get(handles.checkbox_Use_Cropped_Image,'value')
                        cell(l).x=cell(l).x+ax(1)-1;
                        cell(l).y=cell(l).y+ax(3)-1;
                        cell(l).ox=cell(l).ox+ax(1)-1;
                        cell(l).oy=cell(l).oy+ax(3)-1;
                    end
                    cells1(segmentation.frame1,l)=cell(l);
                end
            case 4
                cell=phy_segmentCellsWatershedFormeBF(segmentation.segmentationImage(:,:,segmentation.phaseChannel),segmentation.parametres);
                for l=1:length(cell)
                    cell(l).image=segmentation.frame1;
                    if get(handles.checkbox_Use_Cropped_Image,'value')
                        cell(l).x=cell(l).x+ax(1)-1;
                        cell(l).y=cell(l).y+ax(3)-1;
                        cell(l).ox=cell(l).ox+ax(1)-1;
                        cell(l).oy=cell(l).oy+ax(3)-1;
                    end
                    cells1(segmentation.frame1,l)=cell(l);
                end
        end
            segmentation.cells1Segmented(segmentation.frame1)=1;
            segmentation.frameChanged(segmentation.frame1)=1;
            segmentation.cells1Mapped(segmentation.frame1)=0;
    end
    if ishandle(segmentation.myHandles.showCells)
        delete(segmentation.myHandles.showCells);
        delete(segmentation.myHandles.showCellsText);
    end
    [segmentation.myHandles.showCells segmentation.myHandles.showCellsText]=phy_showObject(handles.axes1,cells1(segmentation.frame1,:),'r','cells1',segmentation.myHandles.showCells,segmentation.myHandles.showCellsText,'on');
    set(segmentation.myHandles.showCells(:),'ButtonDownFcn',{@mouseSelectObject,handles});
    set(segmentation.myHandles.showCells(:),'UIContextMenu',handles.Context_Objects);
end
segmentation.cells1=cells1;
% segmentation.cells2=cells2;
status('Idle',handles);
guidata(hObject, handles);
% --- Executes on button press in pushbutton_segAll.
function pushbutton_segAll_Callback(hObject, eventdata, handles)
global segmentation
global timeLapse
if ~segmentation.play
    %---------------------
    %dialog box
    prompt = {'Enter first frame:','Enter last frame:'};
    dlg_title = 'Segment frames';
    num_lines = 1;
    def = {num2str(segmentation.frame1),num2str(timeLapse.numberOfFrames)};
    %def = {num2str(bSeg(1)),num2str(bSeg(end))};
    answer = inputdlg(prompt,dlg_title,num_lines,def);
    if isempty(answer)
        segmentation.play=false;
        set(hObject,'String','Segment All');
        status('Idle',handles);
        return
    end
    startFrame=str2double(answer(1));
    endFrame=str2double(answer(2));
    %-----------------------
    segmentation.play=true;
    set(hObject,'String','Pause');
    for i=startFrame:endFrame
        Change_Disp1(i,handles);
        segmentation.frame1
        timeStart=tic;
        pushbutton_segImg_Callback(handles.pushbutton_segImg, eventdata, handles)
        toc(timeStart)
        pause(0.2);
        if ~segmentation.play
            break
        end
    end
else
    segmentation.play=false;
    set(hObject,'String','Segment All');
end
segmentation.play=false;
set(hObject,'String','Segment All');
status('Idle',handles);
% --- Executes on button press in pushbutton_saveAll.
function pushbutton_saveAll_Callback(hObject, eventdata, handles)
global timeLapse;
global segmentation
status('Saving',handles);
tic
save(fullfile(timeLapse.path,timeLapse.pathList.position{segmentation.position},'segmentation.mat'),'segmentation');
toc
status('Idle',handles);
% --- Executes on button press in pushbutton_Set_Mother.
function pushbutton_Set_Mother_Callback(hObject, eventdata, handles)
global segmentation
%---------------------------------------------
prompt = {'Enter mother number:'};
dlg_title = 'Mother';
num_lines = 1;
def = {'0'};
answer = inputdlg(prompt,dlg_title,num_lines,def);
if isempty(answer)
    return
end
%--------------------------------------------------
if get(handles.radiobutton_Image,'Value')
    segmentation.selectedObj.mother=str2double((answer{1}));
    %segmentation.frameChanged(segmentation.frame1)=1;
end
if get(handles.radiobutton_All_Images,'Value')&&~isempty(segmentation.selectedTObj)
    m=str2double(answer{1});
    if segmentation.selectedTObj.mother>0
        tobj=segmentation.(['t',segmentation.selectedType]);
        tobj(segmentation.selectedTObj.mother).removeDaughter(segmentation.selectedTObj.N)
        segmentation.(['t',segmentation.selectedType])=tobj;
    end
    segmentation.selectedTObj.setMother(0,0);
    if m~=0
        segmentation.selectedTObj.setMother(m);
        segmentation.selectedTObj.birthFrame=segmentation.selectedTObj.detectionFrame;
        tobj=segmentation.(['t',segmentation.selectedType]);
        divisionStart=segmentation.selectedTObj.detectionFrame;
        divisionEnd=segmentation.selectedTObj.detectionFrame;
        tobj(m).addDaughter(segmentation.selectedTObj.N,divisionStart,divisionEnd);
        segmentation.(['t',segmentation.selectedType])=tobj;
        %segmentation.frameChanged(segmentation.selectedTObj.detectionFrame:segmentation.selectedTObj.lastFrame)=1;
    end
end
if get(handles.radiobutton_From_This_Image,'Value')&&~isempty(segmentation.selectedTObj)
    segmentation.selectedTObj.setMother(0,segmentation.frame1);
    segmentation.selectedTObj.setMother(str2double(answer{1}),segmentation.frame1);
    %segmentation.frameChanged(segmentation.frame1:segmentation.selectedTObj.lastFrame)=1;
end
% --- Executes on button press in pushbutton_Set_Number.
function pushbutton_Set_Number_Callback(hObject, eventdata, handles)
global segmentation
tobj=segmentation.(['t',segmentation.selectedType]);
obj= segmentation.(segmentation.selectedType);
prompt = {'Enter object number:'};
dlg_title = 'Number';
num_lines = 1;
def = {num2str(length(tobj)+1)};
answer = inputdlg(prompt,dlg_title,num_lines,def);
if ~isempty(answer)
    n=str2double(answer);
    if ~isempty(segmentation.selectedTObj) %if not already mapped
        for i=1:size(obj,2)
            if obj(segmentation.frame1,i).n==n && obj(segmentation.frame1,i)~=segmentation.selectedObj
                button = questdlg({'An object with the same number already exist.','Do you want to continue?','(if YES: the object with same numbet will change the number)'},'warning','YES','Cancel','YES') ;
                if strcmp(button,'YES')
                    maxn=length(tobj);
                    tobj(end+1)=phy_Tobject;
                    tobj(n).setNumber(maxn+1);
                    tobj(end)=tobj(n);
                    tobj(n)=phy_Tobject;
                    set(obj(segmentation.frame1,i).htext,'string',num2str(maxn+1));
                    segmentation.(['t',segmentation.selectedType])=tobj;
                    segmentation.frameChanged(tobj(end).detectionFrame:tobj(end).lastFrame)=1;
                else
                    return
                end
            end
        end
    end
    if get(handles.radiobutton_Image,'Value')
        segmentation.selectedObj.n=n;
        if ~isempty(segmentation.selectedTObj)
            tobj=segmentation.(['t',segmentation.selectedType]);
            if length(tobj)<n
                tobj(n)=phy_Tobject;
            end
            tobj(n).addObject(segmentation.selectedObj);
            segmentation.selectedTObj.deleteObject(segmentation.selectedObj,'only from tobject');
            segmentation.(['t',segmentation.selectedType])=tobj;
        end
        segmentation.frameChanged(segmentation.frame1)=1;
    end
    if get(handles.radiobutton_All_Images,'Value')&&~isempty(segmentation.selectedTObj)
        nold=segmentation.selectedTObj.N;
        if n>length(tobj)
            tobj(n)=phy_Tobject;
            tobj(n)=segmentation.selectedTObj;
            tobj(n).setNumber(n);
            tobj(nold)=phy_Tobject;
            segmentation.selectedTObj=tobj(n);
            segmentation.(['t',segmentation.selectedType])=tobj;
            segmentation.frameChanged(tobj(n).detectionFrame:tobj(n).lastFrame)=1;
        end
    end
    if get(handles.radiobutton_From_This_Image,'Value')&&~isempty(segmentation.selectedTObj)
        button = questdlg(['The objects from this image to the end will be atached to the new object,',num2str(n)],'Warning','OK','Cancel','OK') ;
        if strcmp(button,'OK')
            tobj=segmentation.(['t',segmentation.selectedType]);
            if length(tobj)<n
                tobj(n)=phy_Tobject;
            end
            c=0;
            objectMoved=phy_Object;
            for i=1:length(segmentation.selectedTObj.Obj)
                if segmentation.selectedTObj.Obj(i).image>=segmentation.frame1
                    segmentation.selectedTObj.Obj(i).n=n;
                    tobj(n).addObject(segmentation.selectedTObj.Obj(i));
                    c=c+1;
                    objectMoved(c)=segmentation.selectedTObj.Obj(i);
                end
            end
            for i=1:c
                segmentation.selectedTObj.deleteObject(objectMoved(i),'only from tobject');
            end
            segmentation.(['t',segmentation.selectedType])=tobj;
            segmentation.frameChanged(segmentation.frame1:tobj(n).lastFrame)=1;
        end
    end
    set(segmentation.selectedObj.htext,'string',num2str(n));
end
% --- Executes on button press in pushbutton_Delete_Object.
function pushbutton_Delete_Object_Callback(hObject, eventdata, handles)
global segmentation
% if ~isempty(segmentation.selectedTObj)
%     %index=find(segmentation.selectedTObj.C==segmentation.selectedObj);
%     segmentation.selectedTObj.Obj(segmentation.selectedTObj.Obj==segmentation.selectedObj)=[];
% end
% segmentation.selectedObj.ox=0;
% segmentation.selectedObj.oy=0;
% segmentation.selectedObj.n=0;
if get(handles.radiobutton_Image,'Value')
    set([segmentation.selectedObj.htext,segmentation.selectedObj.hcontour],'visible','off');
    if ~isempty(segmentation.selectedTObj)
        segmentation.selectedTObj.deleteObject(segmentation.selectedObj);
    else
        segmentation.selectedObj.ox=0;
        segmentation.selectedObj.oy=0;
        segmentation.selectedObj.n=0;
    end
    segmentation.selectedObj=[];
    segmentation.frameChanged(segmentation.frame1)=1;
end
if get(handles.radiobutton_From_This_Image,'Value')
    if ~isempty(segmentation.selectedTObj)
        button = questdlg({'The objects from this image to the end will be completely deleted.','Are you shure?'},'Warning','Yes','No','Yes') ;
        if strcmpi(button,'Yes')
            set([segmentation.selectedObj.htext,segmentation.selectedObj.hcontour],'visible','off');
            segmentation.selectedTObj.deleteObject(segmentation.frame1);
            segmentation.selectedObj=[];
            segmentation.frameChanged(segmentation.frame1)=1;
        end
    else
        warndlg('No mapping done. To delete use radio button "image"',' Warning');
    end
end
if get(handles.radiobutton_All_Images,'Value')
    if ~isempty(segmentation.selectedTObj)
        button = questdlg({'The objects from the detection frame to the end will be completely deleted.','Are you shure?'},'Warning','Yes','No','Yes') ;
        if strcmpi(button,'Yes')
            set([segmentation.selectedObj.htext,segmentation.selectedObj.hcontour],'visible','off');
            segmentation.selectedTObj.deleteObject('all');
            segmentation.selectedObj=[];
            segmentation.frameChanged(segmentation.frame1)=1;
        end
    else
        warndlg('No mapping done. To delete use radio button "image"',' Warning');
    end
end
% --- Executes on button press in pushbutton_Edit_Contour.
function pushbutton_Edit_Contour_Callback(hObject, eventdata, handles)
global segmentation
set(segmentation.selectedObj.htext,'visible','off');
set(segmentation.selectedObj.hcontour,'visible','off');
[x,y] = getline(handles.axes1,'closed');
segmentation.selectedObj.x=x;
segmentation.selectedObj.y=y;
segmentation.selectedObj.ox=mean(x);
segmentation.selectedObj.oy=mean(y);
segmentation.selectedObj.area=polyarea(x,y);
set(segmentation.selectedObj.hcontour,'xData',x);
set(segmentation.selectedObj.hcontour,'yData',y);
set(segmentation.selectedObj.htext,'position',[mean(x),mean(y)]);
set(segmentation.selectedObj.htext,'visible','on');
set(segmentation.selectedObj.hcontour,'visible','on');
segmentation.frameChanged(segmentation.frame1)=1;
% --- Executes on button press in pushbutton_Create_Object.
function pushbutton_Create_Object_Callback(hObject, eventdata, handles)
global segmentation
% create the dialog box
dim = [3 3]; %number of objects in dialog box
Title = 'Create object';
Prompt = cell(1,2);
Prompt{1,1} = 'Chose the type and the number of the new object';
Formats(1,1).type = 'text';
for k = 2:dim(2) % span the static text across the entire dialog
   Formats(1,k).type = 'none';
   Formats(1,k).limits = [0 1]; % extend from left
end
Prompt(2,:) = {'Choose type of objects','type'};
Formats(2,1).type = 'list';
Formats(2,1).style = 'radiobutton';
Formats(2,1).items = {'Budnecks','Cells1'};
for k = 2:dim(2) % span the static text across the entire dialog
   Formats(2,k).type = 'none';
   Formats(2,k).limits = [0 1]; % extend from left
end
Prompt(3,:) = {'Budneck Number','budneck_number'};
Formats(3,1).type = 'edit';
Formats(3,1).format = 'integer';
Formats(3,1).limits = [0 9999]; % 4-digits (positive #)
Formats(3,1).size = 50;
Prompt(4,:) = {'Cell Number1','cell_number1'};
Formats(3,2).type = 'edit';
Formats(3,2).format = 'integer';
Formats(3,2).limits = [0 9999]; % 4-digits (positive #)
Formats(3,2).size = 50;
%
% Prompt(5,:) = {'Cell Number2','cell_number2'};
% Formats(3,3).type = 'edit';
% Formats(3,3).format = 'integer';
% Formats(3,3).limits = [0 9999]; % 4-digits (positive #)
% Formats(3,3).size = 50;
DefAns.type = 2;
if ~isempty(segmentation.tbudnecks)
    DefAns.budneck_number = length(segmentation.tbudnecks)+1;
else
    DefAns.budneck_number=0;
end
if ~isempty(segmentation.tcells1)
    DefAns.cell_number1 = length(segmentation.tcells1)+1;
else
    DefAns.cell_number1=0;
end
% if ~isempty(segmentation.tcells2)
%     DefAns.cell_number2=length(segmentation.tcells2)+1;
% else
%     DefAns.cell_number2=0;
% end
[Answer,Cancelled] = phy_inputsdlg(Prompt,Title,Formats,DefAns);%Options);
% create the points
if ~Cancelled
%     [x,y] = getline(handles.axes1,'closed');
%     hold(handles.axes1,'on');
%     plot(handles.axes1,x,y);
%     hold(handles.axes1,'off');
    hellipse=imellipse(handles.axes1);
    vertices=wait(hellipse);
    x=vertices(:,1);
    y=vertices(:,2);
    hellipse.delete;
    ox=mean(x);
    oy=mean(y);
    added=false;
    switch Answer.type
        case 1
            n=Answer.budneck_number;
            budn=phy_Object(n,x,y);
            budn.ox=ox;
            budn.oy=oy;
            budn.image=segmentation.frame1;
            budn.area=polyarea(x,y);
            for i=1:length(segmentation.budnecks(segmentation.frame1,:))
                if segmentation.budnecks(segmentation.frame1,i).ox==0
                    segmentation.budnecks(segmentation.frame1,i)=budn;
                    added=true;
                    break;
                end
            end
            if ~added
                segmentation.budnecks(segmentation.frame1,end+1)=budn;
            end
            if n~=0 && ~isempty(segmentation.selectedTObj)
                if n>length(segmentation.tbudnecks)
                    segmentation.tbudnecks(n)=phy_Tobject;
                end
                segmentation.tbudnecks(n).addObject(budn);
            end
        case 2
            n=Answer.cell_number1;
            cellule=phy_Object(n,x,y);
            cellule.ox=ox;
            cellule.oy=oy;
            cellule.image=segmentation.frame1;
            cellule.area=polyarea(x,y);
            for i=1:length(segmentation.cells1(segmentation.frame1,:))
                if segmentation.cells1(segmentation.frame1,i).ox==0
                    segmentation.cells1(segmentation.frame1,i)=cellule;
                    added=true;
                    break;
                end
            end
            if ~added
                segmentation.cells1(segmentation.frame1,end+1)=cellule;
            end
            if n~=0 && ~isempty(segmentation.selectedTObj)
                if n>length(segmentation.tcells1)
                    segmentation.tcells1(n)=phy_Tobject;
                end
                segmentation.tcells1(n).addObject(cellule);
            end
%         case 3
%             n=Answer.cell_number2;
%             cellule=phy_Object(n,x,y);
%             cellule.ox=ox;
%             cellule.oy=oy;
%             cellule.image=segmentation.frame1;
%             cellule.area=polyarea(x,y);
%             for i=1:length(segmentation.cells2(segmentation.frame1,:))
%                 if segmentation.cells2(segmentation.frame1,i).ox==0
%                     segmentation.cells2(segmentation.frame1,i)=cellule;
%                     added=true;
%                     break;
%                 end
%             end
%             if ~added
%                 segmentation.cells2(segmentation.frame1,end+1)=cellule;
%             end
%             if n~=0 && ~isempty(segmentation.selectedTObj)
%                 if n>length(segmentation.tcells1)
%                     segmentation.tcells2(n)=phy_Tobject;
%                 end
%                 segmentation.tcells2(n).addObject(cellule);
%             end
    end
    Change_Disp1('refresh',handles);
    segmentation.frameChanged(segmentation.frame1)=1;
end
% --- Executes on button press in pushbutton_Clear_Image.
function pushbutton_Clear_Image_Callback(hObject, eventdata, handles)
global segmentation
%  if segmentation.cells1Mapped(segmentation.frame1)
% if segmentation.budnecksMapped(segmentation.frame1)
%if get(handles.checkbox_segBud,'Value')
if get(handles.checkbox_segCells,'Value')
    if segmentation.cells1Mapped(segmentation.frame1)
        for i=1:size(segmentation.cells1,2)
            if segmentation.cells1(segmentation.frame1,i).n~=0
                n=segmentation.cells1(segmentation.frame1,i).n;
                segmentation.tcells1(n).deleteObject(segmentation.cells1(segmentation.frame1,i))
            end
        end
    end
    segmentation.cells1(segmentation.frame1,:)=phy_Object;
    segmentation.cells1Segmented(segmentation.frame1)=0;
    segmentation.cells1Mapped(segmentation.frame1)=0;
    segmentation.frameChanged(segmentation.frame1)=1;
    if ishandle(segmentation.myHandles.showCells)
        delete(segmentation.myHandles.showCells);
        delete(segmentation.myHandles.showCellsText);
    end
end
if get(handles.checkbox_segBud,'Value')
    if segmentation.budnecksMapped(segmentation.frame1)
        for i=1:size(segmentation.budnecks,2)
            if segmentation.budnecks(segmentation.frame1,i).n~=0
                n=segmentation.budnecks(segmentation.frame1,i).n;
                segmentation.tbudnecks(n).deleteObject(segmentation.budnecks(segmentation.frame1,i))
            end
        end
    end
    segmentation.budnecks(segmentation.frame1,:)=phy_Object;
    segmentation.budnecksSegmented(segmentation.frame1)=0;
    segmentation.budnecksMapped(segmentation.frame1)=0;
    segmentation.frameChanged(segmentation.frame1)=1;
    if ishandle(segmentation.myHandles.showBudnecks)
        delete(segmentation.myHandles.showBudnecks);
        delete(segmentation.myHandles.showBudnecksText);
    end
end
% --- Executes on button press in pushbutton_Clear_All.
function pushbutton_Clear_All_Callback(hObject, eventdata, handles)
global segmentation
if get(handles.checkbox_segCells,'Value')
    segFrames=find(segmentation.cells1Segmented);
    def = {num2str(segFrames)};
elseif get(handles.checkbox_segBud,'Value')
    segFrames=find(segmentation.budnecksSegmented);
    def = {num2str(segFrames)};
end
    %---------------------------------------
    prompt = {'Enter the frames to clear'};
    dlg_title = 'Frames to clear';
    num_lines = 2;
    answer = inputdlg(prompt,dlg_title,num_lines,def);
    %-----------------------
if ~isempty(answer)&&~isempty(answer{1})
    clearFrames=str2num(answer{1});
    for i=clearFrames
        segmentation.frame1=i;
        pushbutton_Clear_Image_Callback(handles.pushbutton_Clear_Image, eventdata, handles);
    end
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%% SLIDER CALLBACK FUNCTIONS%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function slider1_Callback(hObject, eventdata, handles)
newVal = get(hObject, 'Value');
Change_Disp1(newVal,handles);
function slider1_ButtonDownFcn(hObject, eventdata, handles)
function slider1_CreateFcn(hObject, eventdata, handles)
% Hint: slider controls usually have a light gray background.
if isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor',[.9 .9 .9]);
end
% --- Executes on key press with focus on slider1 and none of its controls.
function slider1_KeyPressFcn(hObject, eventdata, handles)
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%% EDIT CALLBACK FUNCTIONS%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function editFrame1_Callback(hObject, eventdata, handles)
NewStrVal = get(hObject, 'String');
NewVal = str2double(NewStrVal);
Change_Disp1(NewVal,handles);
function edit_Find_Cell_Callback(hObject, eventdata, handles)
global segmentation
if ~isempty(segmentation.selectedTObj)  %if exist a selected tobject then delesect it
    segmentation.selectedTObj.deselect();
    segmentation.selectedTObj={};
end
if ~isempty(segmentation.selectedObj) %if exist a selected object then deselect it
    segmentation.selectedObj.selected=0;
    segmentation.selectedObj={};
end
nCell=str2double(get(hObject,'string')); %get the value of the edit case
if nCell<=length(segmentation.tcells1) && nCell>=1 %if it is in the limits
    if segmentation.tcells1(nCell).N==nCell %check if it was deleted (.N==0)
        segmentation.tcells1(nCell).select(); %select the new cell
        segmentation.selectedTObj=segmentation.tcells1(nCell); % copy it
        if segmentation.tcells1(nCell).detectionFrame==segmentation.frame1 %refresh
            Change_Disp1('refresh',handles);
        else
            Change_Disp1(segmentation.tcells1(nCell).detectionFrame,handles);
        end
    else
        set(hObject,'string','Deleted');
    end
end
function edit_Find_Budneck_Callback(hObject, eventdata, handles)
global segmentation
if ~isempty(segmentation.selectedTObj)
    segmentation.selectedTObj.deselect();
end
nCell=str2double(get(hObject,'string'));
if nCell<=length(segmentation.tbudnecks) && nCell>=1
    segmentation.tbudnecks(nCell).select();
    segmentation.selectedTObj=segmentation.tbudnecks(nCell);
    if segmentation.tbudnecks(nCell).detectionFrame==segmentation.frame1
        Change_Disp1('refresh',handles);
    else
        Change_Disp1(segmentation.tbudnecks(nCell).detectionFrame,handles);
    end
end
% --- Executes during object creation, after setting all properties.
function edit_Find_Budneck_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
% --- Executes during object creation, after setting all properties.
function editFrame1_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
% --- Executes during object creation, after setting all properties.
function edit_Find_Cell_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
% --- Executes during object creation, after setting all properties.
function edit_TCell_Properties_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
% --- Executes during object creation, after setting all properties.
function edit_Cell_Properties_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
function edit_Channel_Poperties_Callback(hObject, eventdata, handles)
% allow to change the color and the saturation on the selected channel
global segmentation
chval=get(handles.listbox_Channels,'Value');
newdata=str2num(get(hObject,'String'));
segmentation.colorData(chval,:)=newdata;
Change_Disp1('refresh',handles);
% --- Executes during object creation, after setting all properties.
function edit_Channel_Poperties_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%% LISTBOX CALLBACK FUNCTIONS%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% --- Executes on selection change in listbox_Channels.
function listbox_Channels_Callback(hObject, eventdata, handles)
global segmentation
butonType=get(handles.figure1,'SelectionType');
chval = get(hObject,'Value');
if strcmp(butonType,'open')  %duble click
    if any(segmentation.channels==chval)   % if already shown
        ind=find(segmentation.channels==chval);  %find the chanel to be made invisible
        for i=ind:length(segmentation.channels)-1    %deplace all the layers from the one to be deleted
            imData=get(segmentation.himg(i+1),'Cdata');
            set(segmentation.himg(i),'Cdata',imData);
        end
        im=zeros(1,1,3);
        set(segmentation.himg(length(segmentation.channels)),'CData',im); %make the last layer invisible
        set(segmentation.himg(length(segmentation.channels)),'Alphadata',0);
        segmentation.channels(ind)=[]; %delete the index from the list
    else  %if is not in the list / not already shown
        segmentation.channels=[segmentation.channels chval]; %add the new channel to the list
        Change_Disp1('refresh',handles);%refresh dislay
    end
end
str=get(hObject,'String');
set(handles.text_Channels,'string',{str{segmentation.channels}});
set(handles.edit_Channel_Poperties,'string',num2str(segmentation.colorData(chval,:),'(%0.1f) (%0.1f) (%0.1f) (%0.4f) (%0.4f) (%0.1f)'));
% --- Executes during object creation, after setting all properties.
function listbox_Channels_CreateFcn(hObject, eventdata, handles)
if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
    set(hObject,'BackgroundColor','white');
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%% MENU FUNCTIONS %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%======================== FILE ==========================================
% --------------------------------------------------------------------
function File_Callback(hObject, eventdata, handles)
% --------------------------------------------------------------------
function File_Open_TimeLapse_Project_Callback(hObject, eventdata, handles)
OpenProject_ClickedCallback(hObject, eventdata, handles);
% --------------------------------------------------------------------
function Create_Project_From_Images_Callback(hObject, eventdata, handles)
phy_createTimeLapseProjectGui();
%============= SEGMENTATION ==============================================
% --------------------------------------------------------------------
function Segmentation_Callback(hObject, eventdata, handles)
% --------------------------------------------------------------------
function Segmentation_SegmentCells_Callback(hObject, eventdata, handles)
set(handles.checkbox_segCells,'value',1);
set(handles.checkbox_segBud,'value',0);
pushbutton_segAll_Callback(handles.pushbutton_segAll, eventdata, handles);
% --------------------------------------------------------------------
1000 function Segmentation_MapCell_Callback(hObject, eventdata, handles)
1001
1002 global segmentation
1003
1004 cSeg1=find(segmentation.cells1Segmented);
1005 %cSeg2=find(segmentation.cell2Segmented);
1006 %---------------------
1007 %dialog box
1008 prompt = {'Enter first frame:','Enter last frame:'};
1009 dlg_title = 'Map all the segmented frames';
1010 num_lines = 1;
1011 %def = {'1',num2str(timeLapse.numberOfFrames)};
1012 def = {num2str(cSeg1(1)),num2str(cSeg1(end))};
1013 answer = inputdlg(prompt,dlg_title,num_lines,def);
1014 if isempty(answer)
1015     return
1016 end
1017 %-----------------------
1018
1019 startFrame=str2double(answer(1));
1020 endFrame=str2double(answer(2));
1021 status('Map Cells',handles);
1022 tic
1023
1024 param=2*segmentation.parametres.cell_diameter;
1025 c=0;
1026 for i=1:length(cSeg1)%(endFrame-startFrame)%get(handles.slider1,'Max')
1027     %x=startFrame+i; %image to start mapping
1028     if cSeg1(i)>=startFrame && cSeg1(i)<=endFrame
1029         x=cSeg1(i);
1030         c=c+1;
1031         if c==1
1032             segmentation.cells1(x,:)=phy_mapObjects(param,segmentation.cells1(x,:));
1033         elseif c==2
1034             segmentation.cells1(x,:)=phy_mapObjects(param,segmentation.cells1(x,:),segmentation.cells1(cSeg1(i-1),:));
1035         elseif c>2
1036             segmentation.cells1(x,:)=phy_mapObjects(param,segmentation.cells1(x,:),segmentation.cells1(cSeg1(i-1),:),segmentation.cells1(cSeg1(i-2),:));
1037         end
1038         segmentation.cells1Mapped(x)=1;
1039         segmentation.frameChanged(x)=1;
1040     end
1041 end
1042 toc
1043
1044 status('Check Cells',handles);
1045 Check_Cells_Callback([], [], handles);
1046
1047
1048
1049 % warningDisparitionCells=[];
1050 % for i=1:length(segmentation.tcells1)
1051 %     if segmentation.tcells1(i).N~=0
1052 %         if segmentation.tcells1(i).lastFrame<cSeg1(end)
1053 %             warningDisparitionCells=[warningDisparitionCells i];
1054 %         end
1055 %     end
1056 % end
1057 % if ~isempty(warningDisparitionCells)
1058 %     warndlg({'The folowing cells are not present on the last segmented frame',num2str(warningDisparitionCells)},...
1059 %         'Warning cell disparition')
1060 % end
1061
1062 status('Idle',handles);
1063
1064 % --------------------------------------------------------------------
1065 function Segmentation_SegmentBudneck_Callback(hObject, eventdata, handles)
1066 set(handles.checkbox_segCells,'value',0);
1067 set(handles.checkbox_segBud,'value',1);
1068 pushbutton_segAll_Callback(handles.pushbutton_segAll, eventdata, handles);
1069
1070
1071 % --------------------------------------------------------------------
1072 function Segmentation_MapBudneck_Callback(hObject, eventdata, handles)
1073
1074 global segmentation
1075 bSeg=find(segmentation.budnecksSegmented);
1076
1077 %---------------------
1078 %dialog box
1079 prompt = {'Enter first frame:','Enter last frame:'};
1080 dlg_title = 'Map all the segmented frames';
1081 num_lines = 1;
1082 %def = {'1',num2str(timeLapse.numberOfFrames)};
1083 def = {num2str(bSeg(1)),num2str(bSeg(end))};
1084 answer = inputdlg(prompt,dlg_title,num_lines,def);
1085 if isempty(answer)
1086     return
1087 end
1088 %-----------------------
1089
1090 startFrame=str2double(answer(1));
1091 endFrame=str2double(answer(2));
1092 status('Map budnecks',handles);
1093 tic
1094
1095 param=2*segmentation.parametres.budneck_diameter;
1096 c=0;
1097 for i=1:length(bSeg)%get(handles.slider1,'Max')
1098     %x=startFrame+i; %image to start mapping
1099     if bSeg(i)>=startFrame && bSeg(i)<=endFrame
1100         x=bSeg(i);
1101         c=c+1;
1102         if c==1
1103             segmentation.budnecks(x,:)=phy_mapObjects(param,segmentation.budnecks(x,:));
1104         elseif c==2
1105             segmentation.budnecks(x,:)=phy_mapObjects(param,segmentation.budnecks(x,:),segmentation.budnecks(bSeg(i-1),:));
1106         elseif c>2
1107             segmentation.budnecks(x,:)=phy_mapObjects(param,segmentation.budnecks(x,:),segmentation.budnecks(bSeg(i-1),:),segmentation.budnecks(bSeg(i-2),:));
1108         end
1109         segmentation.budnecksMapped(x)=1;
1110         segmentation.frameChanged(x)=1;
1111     end
1112 end
1113 toc
1114
1115 Check_Budnecks_Callback([], [], handles)
1116 % status('refresh tbudnecks',handles);
1117 % tic
1118 % [segmentation.tbudnecks fchange]=phy_makeTObject(segmentation.budnecks,segmentation.tbudnecks);
1119 % segmentation.frameChanged(fchange)=1;
1120 % toc
1121 status('Idle',handles);
1122
1123 % --------------------------------------------------------------------
1124 function Segmentation_Setings_Callback(hObject, eventdata, handles)
1125
1126 global segmentation
1127
1128 %check struct saved from previous versions
1129 if ~isfield(segmentation.parametres,'cell_diameter')
1130     segmentation.parametres.cell_diameter=50;
1131 end
1132
1133 if ~isfield(segmentation.parametres,'budneck_diameter')
1134     segmentation.parametres.budneck_diameter=15;
1135 end
1136
1137 if ~isfield(segmentation.parametres,'segmentation')
1138     segmentation.parametres.segmentation=2;
1139 end
1140
1141 if ~isfield(segmentation.parametres,'numberPixelsWat')
1142     segmentation.parametres.numberPixelsWat=50;
1143 end
1144 if ~isfield(segmentation.parametres,'budneckRefine')
1145     segmentation.parametres.budneckRefine=0;
1146 end
1147 %-------------------------------------------------------------------------
1148
1149 %dialog
1150 prompt = {'Enter cell diameter:','Enter budneck diameter:','Enter segmentation method: 1-balon / 2-watershedPH / 3-omothetie /4-watershedBF','Enter the number of pixel to add in watershed before doing an ellipse aproximation:','Enter the refine value for budneck segmentation (-1 to 1):'};
1151 dlg_title = 'Segmentation parametres';
1152 num_lines = 1;
1153 def = {num2str(segmentation.parametres.cell_diameter),num2str(segmentation.parametres.budneck_diameter),num2str(segmentation.parametres.segmentation),num2str(segmentation.parametres.numberPixelsWat),num2str(segmentation.parametres.budneckRefine)};
1154 answer = inputdlg(prompt,dlg_title,num_lines,def);
1155 if isempty(answer)
1156     return
1157 end
1158 %-----------------------
1159
1160 segmentation.parametres.cell_diameter=str2double(answer(1));
1161 segmentation.parametres.budneck_diameter=str2double(answer(2));
1162 segmentation.parametres.segmentation=str2double(answer(3));
1163 segmentation.parametres.numberPixelsWat=str2double(answer(4));
1164 segmentation.parametres.budneckRefine=str2double(answer(5));
1165
1166
1167
1168 %============= PEDIGREE =================================================
1169 % --------------------------------------------------------------------
1170 function Pedigree_Callback(hObject, eventdata, handles)
1171
1172
1173 % --------------------------------------------------------------------
1174 function Pedigree_MakeP_Callback(hObject, eventdata, handles)
1175 global segmentation
1176
1177 status('refresh tbudnecks',handles);
1178 tic
1179 [segmentation.tbudnecks fchange]=phy_makeTObject(segmentation.budnecks,segmentation.tbudnecks);
1180 segmentation.frameChanged(fchange)=1;
1181 toc
1182
1183 status('refresh tcells1',handles);
1184 tic
1185 [segmentation.tcells1 fchange]=phy_makeTObject(segmentation.cells1,segmentation.tcells1);
1186 segmentation.frameChanged(fchange)=1;
1187 toc
1188
1189
1190 firstSegmented=find(segmentation.cells1Segmented,1,'first');%first frame segmented
1191 Change_Disp1(firstSegmented,handles);
1192 pause(0.1);
1193
1194 %---------------------
1195 %dialog box
1196 prompt = {'Enter first mother cell:','Enter others cell in first frame:'};
1197 dlg_title = 'First frame cells';
1198 num_lines = 1;
1199 firstMCell=[];%first mother cell
1200 tcells=segmentation.tcells1;
1201 for i=1:length(tcells)
1202     if tcells(i).detectionFrame==firstSegmented && tcells(i).mother==0
1203         firstMCell=i;
1204         break
1205     end
1206 end
1207
1208 if isempty(firstMCell)
1209     warndlg('There is no cell with no mother in first frame','Warning cell no mother')
1210     return
1211 end
1212 firstCells=[];
1213 for i=1:length(tcells)
1214     if tcells(i).detectionFrame==firstSegmented && tcells(i).N~=firstMCell
1215         firstCells=[firstCells,i];
1216     end
1217 end
1218
1219 %def = {'1',num2str(timeLapse.numberOfFrames)};
1220 def = {num2str(firstMCell),num2str(firstCells)};
1221 answer = inputdlg(prompt,dlg_title,num_lines,def);
1222 if isempty(answer)
1223     return
1224 end
1225
1226 firstMCell=str2double(answer{1});
1227 firstCells=str2num(answer{2});
1228 %-----------------------
1229
1230
1231
1232 fch=find(segmentation.frameChanged);
1233 if isempty(fch)
1234     button = questdlg({'There were no changes on the frames.','Do you realy want to rebuild the pedigree?','(if YES: the masks will be redone)'},'Warning','YES','NO','NO') ;
1235     if strcmpi(button,'YES')
1236         %---------------------------------------
1237         prompt = {'Enter the first frame :','Enter the last frame :'};
1238         dlg_title = 'Frames';
1239         num_lines = 1;
1240         def = {'1','0'};
1241         answer = inputdlg(prompt,dlg_title,num_lines,def);
1242         if isempty(answer)
1243             return
1244         end
1245         %-----------------------
1246         firstFrame=str2double(answer(1));
1247         lastFrame=str2double(answer(2));
1248         fch=firstFrame:lastFrame;
1249
1250     end
1251 end
1252
1253 button = questdlg({'Do you want to celar all the mothers?'},'Warning','Yes','No','No') ;
1254 if strcmpi(button,'Yes')
1255     for i=1:length(segmentation.tcells1)
1256         segmentation.tcells1(i).setMother(0);
1257         segmentation.tcells1(i).mothers=[];
1258     end
1259 end
1260
1261 if segmentation.pedigree.makeType==1
1262     tic
1263     status('Make Pedigree (masks budnecks cells)',handles);
1264     phy_progressbar;
1265     cnt=0;
1266     for i=fch
1267         cnt=cnt+1;
1268         phy_progressbar(cnt/length(fch));
1269         %i=startFrame+x;
1270         %if i>=startFrame && i<=endFrame
1271             if size(segmentation.cells1,1)>=i
1272             cell1=segmentation.cells1(i,:);
1273             else
1274                 cell1=[];
1275                 continue
1276             end
1277 %            cell2=segmentation.cells2(i,:);
1278             if size(segmentation.budnecks,1)>=i
1279             budneck=segmentation.budnecks(i,:);
1280             else
1281                 budneck=[];
1282                 continue
1283             end
1284
1285             masks1=(zeros(size(segmentation.realImage(:,:,1))));
1286
1287             for j=1:length(cell1)
1288                 if cell1(j).n~=0
1289                     bw_cell = poly2mask(cell1(j).x,cell1(j).y,size(segmentation.realImage,1),size(segmentation.realImage,2));
1290                     masks1(bw_cell)=cell1(j).n;
1291                 end
1292             end
1293             %figure;imshow(tot1);
1294
1295             for j=1:length(budneck)
1296                 if segmentation.budnecks(i,j).n~=0
1297                     segmentation.budnecks(i,j).cell1=[];
1298                     %segmentation.budnecks(i,j).cell2=[];
1299                     bw_bud = poly2mask(budneck(j).x,budneck(j).y,size(segmentation.realImage,1),size(segmentation.realImage,2));
1300                     segmentation.budnecks(i,j).cell1=masks1(bw_bud);
1301                     %segmentation.budnecks(i,j).cell2=masks2(bw_bud);
1302                 end
1303             end
1304             segmentation.frameChanged(i)=0;
1305         %end
1306     end
1307     phy_progressbar(1);
1308     pause(0.01);
1309     'masks1'
1310     toc
1311
1312     tic
1313
1314     status('Set mothers',handles);
1315     [segmentation.tcells1 segmentation.tbudnecks]=phy_setMothers(segmentation.tcells1,segmentation.tbudnecks,'cell1',firstMCell,firstCells);
1316     %[segmentation.tcells2 segmentation.tbudnecks]=phy_setMothers(segmentation.tcells2,segmentation.tbudnecks,'cell2');
1317     'find daughter'
1318     toc
1319 else
1320     phy_setMothersWithoutBudneck(fch,firstMCell,firstCells)
1321     status('Set mothers',handles);
1322 end
1323 status('Idle',handles);
1324
1325
1326 % --------------------------------------------------------------------
1327 function Pedigree_Plot_Pedigree_Callback(hObject, eventdata, handles)
1328 global segmentation
1329 hgui=gcf;
1330 [haxe,himg]=phy_plotPedigree(segmentation.tcells1,segmentation.pedigree.plotType);
1331 set(himg,'ButtonDownFcn',{@mousePedigreePlot,handles,haxe});
1332 segmentation.myHandles.pedigreeImage=himg;
1333
1334 % --------------------------------------------------------------------
1335 function Pedigree_Setings_Callback(hObject, eventdata, handles)
1336 % chose some settings for the pedigree
1337 global segmentation
1338 prompt = {'Enter the plot type: 1-color of data; 2-budneck times','Enter the way of making the pedigree: 1-with budnecks; 2-without budnecks'};
1339 dlg_title = 'Pedigree setings';
1340 num_lines = 1;
1341 def = {num2str(segmentation.pedigree.plotType),num2str(segmentation.pedigree.makeType)};
1342
1343 answer = inputdlg(prompt,dlg_title,num_lines,def);
1344 if isempty(answer)
1345     return
1346 end
1347
1348 segmentation.pedigree.plotType=str2double(answer{1});
1349 segmentation.pedigree.makeType=str2double(answer{2});
1350
1351 % --------------------------------------------------------------------
1352 function Pedigree_Clear_Mothers_Callback(hObject, eventdata, handles)
1353 global segmentation
1354
1355 button = questdlg({'Do you want to celar all the mothers?'},'Warning','Yes','No','No') ;
1356 if strcmpi(button,'Yes')
1357     for i=1:length(segmentation.tcells1)
1358         segmentation.tcells1(i).setMother(0);
1359         segmentation.tcells1(i).mothers=[];
1360     end
1361 end
1362
1363
1364 %================= VIEW ==================================================
1365
1366 % --------------------------------------------------------------------
1367 function View_Callback(hObject, eventdata, handles)
1368
1369
1370 % --------------------------------------------------------------------
1371 function View_Edit_Cell_Properties_Callback(hObject, eventdata, handles)
1372 %edit the fields that can be viewed in "Cell Properties"
1373
1374 global segmentation
1375 %build the proprietes for inputdlg
1376 %title
1377 dlg_title = 'Show propreties';
1378 %prompt string
1379 names = fieldnames(phy_Object);
1380 s='Available propreties options: \n';
1381 for i=1:length(names)
1382     if mod(i,4)==0
1383         s=[s,names{i},'\n'];
1384     else
1385         s=[s,names{i},'\t'];
1386     end
1387 end
1388 s=sprintf(s);
1389 prompt={s};
1390
1391 %default value of the string (the last value)
1392 default='';
1393 for i=1:length(segmentation.showFieldsObj)
1394     default=[default,segmentation.showFieldsObj{i},' '];
1395 end
1396 num_lines = 2;
1397 def = {default};
1398
1399 %options
1400 options.Resize='on';
1401
1402 %dialog figure
1403 answer = inputdlg(prompt,dlg_title,num_lines,def,options);
1404 if isempty(answer)
1405     return
1406 end
1407 %save the result
1408 C=textscan(answer{1},'%s');
1409 segmentation.showFieldsObj=C{1};
1410
1411
1412 % --------------------------------------------------------------------
1413 function View_Edit_TCell_Properties_Callback(hObject, eventdata, handles)
1414 %edit the fields that can be viewed in "TCell Properties"
1415
1416 global segmentation
1417
1418 %build the proprietes for inputdlg
1419 %title
1420 dlg_title = 'Show propreties';
1421 %prompt string
1422 names = fieldnames(phy_Object);
1423 s='Available propreties options: \n';
1424 for i=1:length(names)
1425     if mod(i,4)==0
1426         s=[s,names{i},'\n'];
1427     else
1428         s=[s,names{i},'\t'];
1429     end
1430 end
1431 s=sprintf(s);
1432 prompt={s};
1433
1434 %default value of the string (the last value)
1435 default='';
1436 for i=1:length(segmentation.showFieldsTObj)
1437     default=[default,segmentation.showFieldsTObj{i},' '];
1438 end
1439 num_lines = 2;
1440 def = {default};
1441
1442 %options
1443 options.Resize='on';
1444
1445 %dialog figure
1446 answer = inputdlg(prompt,dlg_title,num_lines,def,options);
1447 if isempty(answer)
1448     return
1449 end
1450 %save the result
1451 C=textscan(answer{1},'%s');
1452 segmentation.showFieldsTObj=C{1};
1453
1454
1455 % --------------------------------------------------------------------
1456 function View_Set_Channels_Colors_Callback(hObject, eventdata, handles)
1457 % call the GUI to set the cannels colors
1458 global segmentation
1459 global timeLapse;
1460
1461 set(handles.checkbox_Use_Display_Image,'value',0);
1462 Change_Disp1('refresh',handles);
1463
1464 segmentation.colorData=phy_setColorsGui(segmentation.colorData,segmentation.realImage);
1465 pause(0.1);
1466 %status('Saving to file',handles);
1467 %save(fullfile(timeLapse.path,timeLapse.pathList.position{segmentation.position},'segmentation.mat'),'segmentation','-append');
1468 Change_Disp1('refresh',handles);
1469
1470
1471 %===================== CHECK ============================================
1472
1473 % --------------------------------------------------------------------
1474 function Check_Callback(hObject, eventdata, handles)
1475
1476 % --------------------------------------------------------------------
1477 function Check_Cells_Callback(hObject, eventdata, handles)
1478 global segmentation
1479
1480 cSeg1=find(segmentation.cells1Segmented);
1481
1482 [segmentation.tcells1 fchange]=phy_makeTObject(segmentation.cells1,segmentation.tcells1);
1483
1484
1485
1486 warningDisparitionCells=[];
1487 for i=1:length(segmentation.tcells1)
1488     if segmentation.tcells1(i).N~=0
1489         if segmentation.tcells1(i).lastFrame<cSeg1(end)
1490             warningDisparitionCells=[warningDisparitionCells i];
1491         end
1492     end
1493 end
1494
1495 len=zeros(1,length(segmentation.tcells1));
1496 for i=1:length(segmentation.tcells1)
1497     if segmentation.tcells1(i).N~=0
1498         len(i)=segmentation.tcells1(i).lastFrame-segmentation.tcells1(i).detectionFrame+1;
1499     end
1500 end
1501
1502 if ~isempty(warningDisparitionCells)
1503     str={['The folowing cells are not present on the last segmented frame(',num2str(cSeg1(end)),'): ']};
1504     for i=1:length(segmentation.tcells1)
1505         if len(i)~=0 && any(warningDisparitionCells==i)
1506             str=[str;[num2str(i),'- length :' ,num2str(len(i))]];
1507         end
1508     end
1509     warndlg(str,'Warning cell disparition')
1510 end
1511
1512 lostCells=[];
1513 str={'The folowing cells have lost frames: '};
1514 for i=1:length(segmentation.tcells1)
1515     if segmentation.tcells1(i).N~=0
1516         frames=segmentation.tcells1(i).lostFrames;
1517         if ~isempty(frames)
1518             lostCells=[lostCells i];
1519             str=[str;[num2str(i),'- frames :' ,num2str(frames)]];
1520         end
1521     end
1522 end
1523 if ~isempty(lostCells)
1524     warndlg(str,'Warning cell frame disparition');
1525 end
1526
1527 if isempty(warningDisparitionCells)&&isempty(lostCells)
1528     warndlg('Cells are OK','OK');
1529 end
1530
1531
1532 % --------------------------------------------------------------------
1533 function Check_Budnecks_Callback(hObject, eventdata, handles)
1534 global segmentation
1535
1536 %bSeg=find(segmentation.budnecksSegmented);
1537
1538 status('refresh tbudnecks',handles);
1539 tic
1540 [segmentation.tbudnecks fchange]=phy_makeTObject(segmentation.budnecks,segmentation.tbudnecks);
1541 toc
1542 status('Idle',handles);
1543
1544 lostBudnecks=[];
1545 str={'The folowing budnecks have lost frames: '};
1546 for i=1:length(segmentation.tbudnecks)
1547     if segmentation.tbudnecks(i).N~=0
1548         frames=segmentation.tbudnecks(i).lostFrames;
1549         if ~isempty(frames)
1550             lostBudnecks=[lostBudnecks i];
1551             str=[str;[num2str(i),'- frames :' ,num2str(frames)]];
1552         end
1553     end
1554 end
1555 if ~isempty(lostBudnecks)
1556     warndlg(str,'Warning budnecks frame disparition');
1557 end
1558
1559 len=zeros(1,length(segmentation.tbudnecks));
1560 for i=1:length(segmentation.tbudnecks)
1561     if segmentation.tbudnecks(i).N~=0
1562         len(i)=segmentation.tbudnecks(i).lastFrame-segmentation.tbudnecks(i).detectionFrame+1;
1563     end
1564 end
1565
1566 meanLength=mean(len(len~=0));
1567 sdLength=std(len(len~=0));
1568
1569 lengthError=false;
1570 str={['The folowing budnecks have wierd time of life: (mean=', num2str(meanLength),')']};
1571 for i=1:length(segmentation.tbudnecks)
1572     if len(i)~=0 && (len(i)> segmentation.check.budneckTimeHigh || len(i)<segmentation.check.budneckTimeLow)
1573         str=[str;[num2str(i),'- length :' ,num2str(len(i))]];
1574         lengthError=true;
1575     end
1576 end
1577 if lengthError
1578     warndlg(str,'Warning budnecks frame disparition');
1579 end
1580 if isempty(lostBudnecks)&&~lengthError
1581     warndlg('Budnecks are OK','OK');
1582 end
1583
1584
1585
1586 %===================== EXPORT ============================================
1587 % --------------------------------------------------------------------
1588 function Export_Data_To_File_Callback(hObject, eventdata, handles)
1589 global segmentation;
1590 global timeLapse;
1591 divisionTime=[];
1592 buddedTime=[];
1593 nonBudedTime=[];
1594 areaDivision=[];
1595 areaBudneck=[];
1596 for i=1:length(segmentation.tcells1)
1597     div=[segmentation.tcells1(i).birthFrame segmentation.tcells1(i).divisionTimes];
1598     divt=diff(div);
1599     budt=segmentation.tcells1(i).divisionTimes-segmentation.tcells1(i).budTimes;
1600     if div(end)==segmentation.tcells1(i).lastFrame && numel(divt)~=0
1601         divt(end)=[];
1602         budt(end)=[];
1603     end
1604     nbudt=[segmentation.tcells1(i).budTimes(:)]'-div(1:end-1);
1605     ad=[];
1606     for f=divt
1607         for j=1:length(segmentation.tcells1(i).Obj)
1608             if segmentation.tcells1(i).Obj(j).image==f
1609                 ad=[ad round(segmentation.tcells1(i).Obj(j).area)];
1610                 break
1611             end
1612         end
1613     end
1614
1615     ab=[];
1616     for f=segmentation.tcells1(i).budTimes
1617         for j=1:length(segmentation.tcells1(i).Obj)
1618             if segmentation.tcells1(i).Obj(j).image==f
1619                 ab=[ab round(segmentation.tcells1(i).Obj(j).area)];
1620                 break
1621             end
1622         end
1623     end
1624
1625     for j=1:length(divt)
1626         divisionTime(i,j)=divt(j);
1627     end
1628     for j=1:length(budt)
1629         buddedTime(i,j)=budt(j);
1630     end
1631     for j=1:length(nbudt)
1632         nonBudedTime(i,j)=nbudt(j);
1633     end
1634     for j=1:length(ad)
1635         areaDivision(i,j)=ad(j);
1636     end
1637     for j=1:length(ab)
1638         areaBudneck(i,j)=ab(j);
1639     end
1640     datName=fullfile(timeLapse.path,timeLapse.pathList.position{segmentation.position},'divisionTime.csv');
1641     phy_cell2csv(datName,divisionTime,',',1);
1642
1643     datName=fullfile(timeLapse.path,timeLapse.pathList.position{segmentation.position},'buddedTime.csv');
1644     phy_cell2csv(datName,buddedTime,',',1);
1645
1646     datName=fullfile(timeLapse.path,timeLapse.pathList.position{segmentation.position},'nonBudedTime.csv');
1647     phy_cell2csv(datName,nonBudedTime,',',1);
1648
1649     datName=fullfile(timeLapse.path,timeLapse.pathList.position{segmentation.position},'areaDivision.csv');
1650     phy_cell2csv(datName,areaDivision,',',1);
1651
1652     datName=fullfile(timeLapse.path,timeLapse.pathList.position{segmentation.position},'areaBudneck.csv');
1653     phy_cell2csv(datName,areaBudneck,',',1);
1654
1655 end
1656
1657
1658 % --------------------------------------------------------------------
1659 function Export_frame_to_image_Callback(hObject, eventdata, handles)
1660
1661 dir=handles.exportDir;
1662 name=['frame',get(handles.editFrame1,'string')];
1663 fileName=fullfile(dir,name);
1664 [name,dir] = uiputfile({'*.png';'*.bmp';'*.jpg';'*.tif'},'Save Image',fileName);
1665 if name==0
1666     return
1667 end
1668 handles.exportDir=dir;
1669
1670 fileName=fullfile(dir,name);
1671 f=getframe(handles.axes1);
1672 [x,map]=frame2im(f);
1673 imwrite(x,fileName);
1674 guidata(hObject, handles);
1675
1676
1677  %--------------------------------------------------------------------
1678 function Export_frames_to_movie_Callback(hObject, eventdata, handles)
1679 global segmentation
1680 status('Making movie',handles);
1681 dir=handles.exportDir;
1682 name=['movie',get(handles.editFrame1,'string')];
1683 fileName=fullfile(dir,name);
1684 [name,dir] = uiputfile({'*.avi';'*.mat'},'Save movie',fileName);
1685 if name==0
1686     return
1687 end
1688 handles.exportDir=dir;
1689 fileName=fullfile(dir,name);
1690
1691 %---------------------
1692 %dialog box
1693 prompt = {'Enter first frame:','Enter last frame:'};
1694 dlg_title = 'Movie frames';
1695 num_lines = 1;
1696 def = {'1',num2str(segmentation.frame1)};
1697 %def = {num2str(bSeg(1)),num2str(bSeg(end))};
1698 answer = inputdlg(prompt,dlg_title,num_lines,def);
1699 if isempty(answer)
1700     return
1701 end
1702 startFrame=str2double(answer(1));
1703 endFrame=str2double(answer(2));
1704 %-----------------------
1705 movieCount=0;
1706 for i=startFrame:endFrame
1707     Change_Disp1(i,handles);
1708     disp(segmentation.frame1);
1709
1710     movieCount=movieCount+1;
1711     F(movieCount)=getframe(handles.axes1);
1712     pause(0.2);
1713
1714 end
1715
1716 [pathstr, name, ext, versn] = fileparts(fileName);
1717 if strcmpi(ext,'.avi');
1718     movie2avi(F,fileName);
1719 elseif strcmpi(ext,'.mat');
1720     save(fileName,'F');
1721 end
1722
1723 status('Idle',handles);
1724 guidata(hObject, handles);
1725
1726 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1727 %%%%%%%%%%%%%%%%%%%%%%%%% TOOLBAR CLICKED CALLBACK FUNCTIONS %%%%%%%%%%%%%
1728 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1729
1730 % --------------------------------------------------------------------
1731 function OpenProject_ClickedCallback(hObject, eventdata, handles)
1732 global timeLapse;
1733 global segmentation
1734
1735 %check if some projects already oppened
1736 if exist('phy_openedProjects.mat','file')
1737     load('phy_openedProjects.mat')
1738     handles.openedProjects=openedProjects;
1739 end
1740
1741 if isempty(handles.openedProjects)
1742     [timeLapsefile, timeLapsepath] = uigetfile({'*.mat';'*.*'},'Get timelapse file');
1743     if timeLapsefile==0 %if the user not press cancel
1744         return
1745     end
1746
1747     strPath=strcat(timeLapsepath,timeLapsefile);
1748     status('loading timeLapse project',handles);
1749     load(strPath);
1750
1751     if ~isfield(timeLapse,'path') %if the user loaded a valid timelapse project
1752         return
1753     end
1754
1755     timeLapse.path=timeLapsepath;
1756     timeLapse.realPath=timeLapsepath;
1757
1758     %dialog box for entering the position
1759     %------------------------------------
1760     prompt = {'Enter position:'};
1761     dlg_title = 'Position';
1762     num_lines = 1;
1763     def = {'1'};
1764     val=0;
1765     while ~val
1766
1767         answer = inputdlg(prompt,dlg_title,num_lines,def);
1768         if isempty(answer)
1769             return
1770         end
1771         try
1772             segmentation.position=str2double(answer{1});
1773             img=phy_loadTimeLapseImage(segmentation.position,1,1,'non retreat');
1774             val=1;
1775         catch
1776             status('wrong position',handles);
1777             prompt = {'Enter a valid position:'};
1778         end
1779     end
1780     %---------------------------------------------
1781     handles.openedProjects={};
1782     handles.openedProjects={strPath,segmentation.position};
1783 else
1784     project=phy_openProjectGui(handles.openedProjects);
1785     if isempty(project)
1786         return
1787     end
1788     if isempty(project{1,1})
1789         [file, path] = uigetfile({'*.mat';'*.*'},'Get timelapse file',handles.openedProjects{end,1});
1790         if file==0 %if the user not press cancel
1791             return
1792         end
1793         strPath=strcat(path,file);
1794         load(strPath);
1795         if ~isfield(timeLapse,'path') %if the user loaded a valid timelapse project
1796             return
1797         end
1798         strPath=strcat(path,file);
1799         timeLapse.path=path;
1800         timeLapse.realPath=path;
1801
1802         %dialog box for entering the position
1803         %------------------------------------
1804         prompt = {'Enter position:'};
1805         dlg_title = 'Position';
1806         num_lines = 1;
1807         def = {'1'};
1808         val=0;
1809         while ~val
1810             answer = inputdlg(prompt,dlg_title,num_lines,def);
1811             if isempty(answer)
1812                 return
1813             end
1814             try
1815                 segmentation.position=str2double(answer{1});
1816                 img=phy_loadTimeLapseImage(segmentation.position,1,1,'non retreat');
1817                 val=1;
1818             catch
1819                 status('wrong position',handles);
1820                 prompt = {'Enter a valid position:'};
1821             end
1822         end
1823         %---------------------------------------------
1824         handles.openedProjects=[handles.openedProjects;{strPath,segmentation.position}];
1825     else
1826         str=project{1};
1827
1828         load(str);
1829         str=project{1};
1830         [pathstr, name, ext, versn] = fileparts(str);
1831         path=[pathstr,'/'];
1832         timeLapse.path=path;
1833         timeLapse.realPath=path;
1834
1835         segmentation.position=project{2};
1836         img=phy_loadTimeLapseImage(segmentation.position,1,1,'non retreat');
1837
1838     end
1839
1840 end
1841
1842 openedProjects=handles.openedProjects;
1843 save('phy_openedProjects.mat','openedProjects');
1844
1845 if exist(fullfile(timeLapse.path,timeLapse.pathList.position{segmentation.position},'segmentation.mat'),'file')
1846     status('loading saved file segmentation',handles);
1847     tic
1848     load(fullfile(timeLapse.path,timeLapse.pathList.position{segmentation.position},'segmentation.mat'))
1849     toc
1850
1851     status('refresh tbudnecks',handles);
1852     tic
1853     [segmentation.tbudnecks fchange]=phy_makeTObject(segmentation.budnecks,segmentation.tbudnecks);
1854     segmentation.frameChanged(fchange)=1;
1855     toc
1856
1857     status('refresh tcells1',handles);
1858     tic
1859     [segmentation.tcells1 fchange]=phy_makeTObject(segmentation.cells1,segmentation.tcells1);
1860     segmentation.frameChanged(fchange)=1;
1861     toc
1862
1863 %     status('refresh segmentation.tcells2',handles);
1864 %     tic
1865 %     [segmentation.tcells2 fchange]=phy_makeTObject(segmentation.cells2,segmentation.tcells2);
1866 %     segmentation.frameChanged(fchange)=1;
1867 %     toc
1868     status('Idle',handles);
1869 else
1870     status('creating the segemntation file',handles);
1871     segmentation.cells1=phy_Object;
1872     %segmentation.cells1(1:timeLapse.numberOfFrames)=phy_Object;
1873     segmentation.cells1Segmented=zeros(1,timeLapse.numberOfFrames);
1874     %segmentation.cells2=phy_Object;
1875     %segmentation.cells2(1:timeLapse.numberOfFrames)=phy_Object;
1876     %segmentation.cell2Segmented=zeros(1,timeLapse.numberOfFrames);
1877     segmentation.budnecks=phy_Object;
1878     %segmentation.budnecks(1:timeLapse.numberOfFrames)=phy_Object;
1879     segmentation.budnecksSegmented=zeros(1,timeLapse.numberOfFrames);
1880     segmentation.tcells1=phy_Tobject;
1881     %segmentation.tcells2=phy_Tobject;
1882     segmentation.tbudnecks=phy_Tobject;
1883
1884     segmentation.cells1Mapped=zeros(1,timeLapse.numberOfFrames);
1885     segmentation.budnecksMapped=zeros(1,timeLapse.numberOfFrames);
1886
1887     nch=length(timeLapse.pathList.channels(1,:));
1888
1889     segmentation.colorData=zeros(nch,6);
1890     segmentation.colorData(:,[1 2 3 5])=1;
1891     segmentation.colorData(:,6)=2;
1892     segmentation.phaseChannel=1;
1893     segmentation.budneckChannel=2;
1894
1895     %segmentation settings
1896     segmentation.parametres.budneck_diameter=15;
1897     segmentation.parametres.cell_diameter=50;
1898     segmentation.parametres.segmentation=2;
1899     segmentation.parametres.numberPixelsWat=50; %number of pixel to add in watershed before doing an ellipse aproximation
1900     segmentation.parametres.budneckRefine=0; %refine budneck segmentation [-1,1]
1901
1902     %pedigree settings default values
1903     segmentation.pedigree.plotType=2;
1904     segmentation.pedigree.makeType=1;
1905
1906     %check settings default values
1907     segmentation.check.budneckTimeLow=5;
1908     segmentation.check.budneckTimeHigh=20;
1909
1910     segmentation.frame1=1;
1911
1912     segmentation.frameChanged=zeros(1,timeLapse.numberOfFrames);
1913
1914     segmentation.showFieldsObj={'n','area','ox','oy','image','mother','selected','dependentData','cell2'};
1915     segmentation.showFieldsTObj={'N','detectionFrame','birthFrame','lastFrame','mother','mothers','daughterList','divisionTimes','budTimes','selected'};
1916
1917
1918     save(fullfile(timeLapse.path,timeLapse.pathList.position{segmentation.position},'segmentation.mat'),'segmentation');
1919     status('idle',handles);
1920 end
1921
1922 nch=length(timeLapse.pathList.channels(1,:));
1923 %dialog box for entering the position
1924 %------------------------------------
1925 prompt = {'Enter phase channel(0 if not existent)','Enter budneck channel(0 if not existent)'};
1926 dlg_title = 'Phase/budneck channel';
1927 num_lines = 1;
1928 pc=segmentation.phaseChannel;
1929 bc=segmentation.budneckChannel;
1930 def = {num2str(segmentation.phaseChannel),num2str(segmentation.budneckChannel)};
1931 val=0;
1932 while ~val
1933
1934     answer = inputdlg(prompt,dlg_title,num_lines,def);
1935     if isempty(answer)
1936         return
1937     end
1938     val=1;
1939     segmentation.phaseChannel=str2double(answer{1});
1940     segmentation.budneckChannel=str2double(answer{2});
1941     if segmentation.phaseChannel==segmentation.budneckChannel
1942         status('wrong channel',handles);
1943         prompt = {'Enter a diferent phase channel or','Enter a diferent budneck channel'};
1944         val=0;
1945     end
1946     if segmentation.phaseChannel>nch || segmentation.phaseChannel<0
1947         status('wrong channel',handles);
1948         prompt = {'Enter a valid phase channel','Enter budneck channel'};
1949         val=0;
1950     end
1951     if segmentation.budneckChannel>nch || segmentation.budneckChannel<0
1952         status('wrong channel',handles);
1953         prompt = {'Enter phase channel','Enter a valid budneck channel'};
1954         val=0;
1955     end
1956 end
1957 %---------------------------------------------
1958 if segmentation.phaseChannel~=pc || segmentation.budneckChannel~=bc
1959 status('saving to file',handles);
1960 save(fullfile(timeLapse.path,timeLapse.pathList.position{segmentation.position},'segmentation.mat'),'segmentation','-append');
1961 status('idle',handles);
1962 end
1963 img_size=size(img);
1964 nch=length(timeLapse.pathList.channels(1,:));
1965
1966
1967 hold(handles.axes1,'on');
1968 str={};
1969 for i=1:nch
1970     img=phy_loadTimeLapseImage(segmentation.position,segmentation.frame1,i,'non retreat');
1971     classimg=class(img);
1972     img_size=max(img_size,size(img));
1973     img=phy_scale(img);
1974     img=repmat(img,[1,1,3]);
1975     segmentation.himg(i)=imshow(img,'Parent',handles.axes1);
1976     str=[str;['channel',num2str(i)]];
1977 end
1978
1979
1980 hold(handles.axes1,'off');
1981
1982 set(handles.listbox_Channels,'string',str);
1983 set(handles.text_Channels,'string',str);
1984
1985 segmentation.channels=1:nch;
1986 segmentation.realImage=zeros([img_size,nch],classimg);
1987 segmentation.segmentationImage=zeros([img_size,nch],class(img));
1988 segmentation.sizeImageMax=img_size;
1989
1990 timeLapse.currentFrame=0;
1991 timeLapse.currentFrame2=0;
1992
1993 segmentation.v_axe1=[0    img_size(2)   0    img_size(1)];
1994 segmentation.v_axe2=[0    img_size(2)   0    img_size(1)];
1995
1996 segmentation.myHandles.showBudnecks=[];
1997 segmentation.myHandles.showBudnecksText=[];
1998 segmentation.myHandles.showCells=[];
1999 segmentation.myHandles.showCellsText=[];
2000 segmentation.myHandles.showCells2=[];
2001 segmentation.myHandles.showCells2Text=[];
2002 segmentation.myHandles.showPedigree2=[];
2003 segmentation.myHandles.showPedigree1=[];
2004
2005 segmentation.selectedTObj={};
2006 segmentation.selectedObj={};
2007 segmentation.copyedObj={};
2008
2009 set(handles.listbox_Channels,'value',1)
2010 set(handles.Segmentation,'Enable','on');
2011 set(handles.Pedigree,'Enable','on');
2012 set(handles.uipanel_Segmentation,'Visible','on');
2013 set(handles.slider1,'Max',timeLapse.numberOfFrames);
2014 %        set(handles.slider2,'Max',timeLapse.numberOfFrames);
2015 status('displaing the channels',handles);
2016 Change_Disp1(segmentation.frame1,handles);
2017 % Change_Disp2(2,handles);
2018
2019 guidata(hObject, handles);
2020 status('Idle',handles);
2021
2022
2023 % --------------------------------------------------------------------
2024 function NewProject_ClickedCallback(hObject, eventdata, handles)
2025 %
2026 phy_createTimeLapseProjectGui();
2027
2028
2029
2030
2031 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2032 %%%%%%%%%%%%%%%%%%%%%%%%% CHECKBOX CALLBACK FUNCTIONS %%%%%%%%%%%%%%%%%%%%
2033 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2034
2035
2036
2037 function handles=checkbox_ShowCells_Callback(hObject, eventdata, handles)
2038 %show the cells1 by first segmentation on the first display
2039 global segmentation
2040
2041
2042 %AppData=getappdata(handles.figure1);
2043 if size(segmentation.cells1,1)>=segmentation.frame1 %check if the image was segmented
2044     if get(hObject,'Value') %if checked
2045         [segmentation.myHandles.showCells segmentation.myHandles.showCellsText]=phy_showObject(handles.axes1,segmentation.cells1(segmentation.frame1,:),'r','cells1',segmentation.myHandles.showCells,segmentation.myHandles.showCellsText,'on');
2046         set(segmentation.myHandles.showCells(:),'ButtonDownFcn',{@mouseSelectObject,handles});
2047         set(segmentation.myHandles.showCells(:),'UIContextMenu',handles.Context_Objects);
2048          %set(segmentation.myHandles.showCells(:),'userdata',segmentation.cells1(segmentation.frame1,:));
2049     else %if not checked
2050         [segmentation.myHandles.showCells segmentation.myHandles.showCellsText]=phy_showObject(handles.axes1,segmentation.cells1(segmentation.frame1,:),'r','cells1',segmentation.myHandles.showCells,segmentation.myHandles.showCellsText,'off');
2051     end
2052 end
2053 %setappdata(handles.figure1,'AppData',AppData);
2054 guidata(hObject, handles); % Save the structure
2055
2056
2057
2058 function handles=checkbox_ShowBudneck_Callback(hObject, eventdata, handles)
2059 global segmentation
2060
2061 if size(segmentation.budnecks,1)>=segmentation.frame1 %check if the image was segmented
2062     if get(hObject,'Value') %if checked
2063         [segmentation.myHandles.showBudnecks segmentation.myHandles.showBudnecksText]...
2064             =phy_showObject(handles.axes1,segmentation.budnecks(segmentation.frame1,:),'b','budnecks',segmentation.myHandles.showBudnecks,segmentation.myHandles.showBudnecksText,'on');
2065         set(segmentation.myHandles.showBudnecks(:),'ButtonDownFcn',{@mouseSelectObject,handles});
2066         set(segmentation.myHandles.showBudnecks(:),'UIContextMenu',handles.Context_Objects);
2067     else %if not checked
2068         [segmentation.myHandles.showBudnecks segmentation.myHandles.showBudnecksText]...
2069             =phy_showObject(handles.axes1,segmentation.budnecks(segmentation.frame1,:),'b','budnecks',segmentation.myHandles.showBudnecks,segmentation.myHandles.showBudnecksText,'off');
2070     end
2071 end
2072 guidata(hObject, handles);% Save the structure
2073
2074 % --- Executes on button press in checkbox_ShowCells2.
2075 function handles=checkbox_ShowCells2_Callback(hObject, eventdata, handles)
2076
2077 % --- Executes on button press in checkbox_Show_Pedigree.
2078 function handles=checkbox_Show_Pedigree_Callback(hObject, eventdata, handles)
2079
2080 global segmentation
2081
2082 if size(segmentation.cells1,1)>=segmentation.frame1 %test if the image already segmented
2083     if get(hObject,'Value') %if checked
2084         segmentation.myHandles.showPedigree1=phy_showPedigree(handles.axes1,segmentation.cells1(segmentation.frame1,:),segmentation.myHandles.showPedigree1,'on');
2085     else
2086         segmentation.myHandles.showPedigree1=phy_showPedigree(handles.axes1,segmentation.cells1(segmentation.frame1,:),segmentation.myHandles.showPedigree1,'off');
2087     end
2088 end
2089
2090 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2091 %%%%%%%%%%%%%%%%%%%%%%%%% OWN FUNCTIONS %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2092 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2093
2094
2095 function Change_Disp1(pos,handles)
2096 %change all the buttons, sliders edittxe related to axex1
2097
2098 global timeLapse;
2099 global segmentation
2100
2101
2102 if strcmpi(pos,'refresh')
2103     timeLapse.currentFrame=0;
2104     pos=segmentation.frame1;
2105 end
2106
2107 Min=get(handles.slider1,'Min');
2108 Max=get(handles.slider1,'Max');
2109
2110 if isempty(pos)
2111     pos=segmentation.frame1;
2112 end
2113 if (pos< Min)
2114     pos=Min;
2115 end
2116 if (pos>Max)
2117     pos=Max;
2118 end
2119 % Check that the entered value falls within the allowable range.
2120 set(handles.editFrame1,'String',round(pos));
2121 set(handles.slider1,'Value',pos);
2122
2123
2124 segmentation.frame1=round(pos);
2125
2126 if isfield(timeLapse,'numberOfFrames')
2127     if segmentation.frame1~=timeLapse.currentFrame
2128         status('Displaying ...',handles);
2129
2130         segmentation.myHandles.showCells=[];
2131         segmentation.myHandles.showBudnecks=[];%clear contours from previous image
2132
2133         timeLapse.currentFrame=segmentation.frame1;
2134         nch=length(timeLapse.pathList.channels(1,:));%n chanels
2135
2136         segmentation.segmentationImage=zeros(size(segmentation.realImage),class(segmentation.realImage));
2137
2138         for i=1:nch
2139             if length(segmentation.channels)>=i %for displayed images load the image
2140
2141                 img=phy_loadTimeLapseImage(segmentation.position,segmentation.frame1,segmentation.channels(i),'non retreat');
2142                 img=imresize(img,segmentation.sizeImageMax);
2143                 segmentation.realImage(:,:,segmentation.channels(i))=img;
2144                 if segmentation.colorData(segmentation.channels(i),4)>=segmentation.colorData(segmentation.channels(i),5)
2145                     segmentation.colorData(segmentation.channels(i),5)=segmentation.colorData(segmentation.channels(i),4)+0.001;
2146                 end
2147                 img=imadjust(img,segmentation.colorData(segmentation.channels(i),[4 5]),[]);
2148
2149                 if get(handles.checkbox_Use_Display_Image,'value')
2150
2151                     I2=img;
2152
2153                 else
2154                     I2=segmentation.realImage(:,:,segmentation.channels(i));
2155                     %img=imadjust(img,segmentation.colorData(segmentation.channels(i),[4 5]),[]);
2156                 end
2157
2158                 if i==1 && get(handles.checkbox_Use_Cropped_Image,'value') %crop
2159                     ax=floor(segmentation.v_axe1); %the axes
2160                     s1=size(img,1);
2161                     s2=size(img,2);
2162                     segmentation.segmentationImage=zeros([min(ax(4)-ax(3)+1,s1),min(ax(2)-ax(1)+1,s2),nch],class(segmentation.segmentationImage));
2163
2164                     I2=imcrop(I2, [ax(1),ax(3),ax(2)-ax(1),ax(4)-ax(3)]);
2165                     segmentation.segmentationImage(:,:,segmentation.channels(i))=I2;
2166                 elseif get(handles.checkbox_Use_Cropped_Image,'value')
2167                     I2=imcrop(I2, [ax(1),ax(3),ax(2)-ax(1),ax(4)-ax(3)]);
2168                     segmentation.segmentationImage(:,:,segmentation.channels(i))=I2;
2169                 else
2170                     segmentation.segmentationImage(:,:,segmentation.channels(i))=I2;
2171                 end
2172
2173                 %create rgb image
2174                 RGB=segmentation.colorData(segmentation.channels(i),[1 2 3]);
2175                 imgRGB=cat(3,img*RGB(1),img*RGB(2),img*RGB(3));
2176
2177                 %set(segmentation.himg(i),'Cdata',imgRGB);
2178                 segmentation.himg(i)=imshow(imgRGB,'Parent',handles.axes1);
2179                 if i==1
2180                     set(segmentation.himg(i),'AlphaData',1);
2181                     hold(handles.axes1,'on');
2182                 else
2183                     if segmentation.colorData(segmentation.channels(i),6)==2
2184                         set(segmentation.himg(i),'AlphaData',img);
2185                     else
2186                         set(segmentation.himg(i),'AlphaData',segmentation.colorData(segmentation.channels(i),6));
2187                     end
2188                 end
2189             else %for non displayed channels use an empty image
2190                 im=zeros(1,1,3);
2191                 segmentation.himg(i)=imshow(im,'Parent',handles.axes1);
2192                 if i==1
2193                     set(segmentation.himg(i),'AlphaData',1);
2194                     hold(handles.axes1,'on');
2195                 else
2196                     set(segmentation.himg(i),'AlphaData',0);
2197                 end
2198
2199             end
2200             set(segmentation.himg(i),'ButtonDownFcn',{@mouseAxesImage,handles});
2201             set(segmentation.himg(i),'UIContextMenu',handles.Context_Image);
2202         end
2203         hold(handles.axes1,'off');
2204         axis(handles.axes1,segmentation.v_axe1);
2205
2206
2207         handles=checkbox_Show_Pedigree_Callback(handles.checkbox_Show_Pedigree, [], handles);
2208
2209         handles=checkbox_ShowCells_Callback(handles.checkbox_ShowCells, [], handles);%if the case is checked then show the segmentation.cells1 by first segmentation
2210
2211         handles=checkbox_ShowBudneck_Callback(handles.checkbox_ShowBudneck, [], handles); %if the case is checked then show the budnecks
2212
2213         segmentation.selectedObj={};
2214         segmentation.selectedTObj={};
2215                 hselected=findobj('Selected','on');
2216         if isempty(hselected)
2217             set(handles.edit_Cell_Properties,'string',[]);
2218             %set(handles.edit_TCell_Properties,'string',[]);
2219         else
2220             mouseSelectObject(hselected(1), 1, handles);
2221         end
2222
2223
2224
2225         status('Idle',handles);
2226     end
2227     segmentation.v_axe1=axis(handles.axes1);
2228 end
2229 uicontrol(handles.pushbutton_Next1); %give focus to buton next (key pres when slider has focux)
2230
2231
2232 % ------------------------------------------------------------------------
2233 function mouseFcn(hObject, eventdata, handles)
2234 %called by zoom and pan functions
2235 %mouse motion sensible function
2236 %change all the values on the frame panel
2237
2238 newVal = get(handles.slider1, 'Value');
2239 Change_Disp1(newVal,handles);
2240 set(handles.checkbox_Use_Cropped_Image,'value',0);
2241
2242
2243 % ------------------------------------------------------------------------
2244 function checkBoxChannel_first(hObject, eventdata, handles)
2245 global timeLapse
2246 global segmentation;
2247 timeLapse.currentFrame=0;
2248 Change_Disp1(segmentation.frame1,handles);
2249
2250 % ------------------------------------------------------------------------
2251 function editChannel_first(hObject, eventdata, handles)
2252 global timeLapse
2253 global segmentation;
2254 timeLapse.currentFrame=0;
2255 Change_Disp1(segmentation.frame1,handles);
2256
2257 % ------------------------------------------------------------------------
2258 function mousePedigreePlot(hObject, eventdata, handles,haxe)
2259 % use to get the cells by duble clicking on the pedigree plot
2260 global segmentation
2261
2262 if ~isempty(segmentation.selectedTObj)  %if exist a selected tobject then delesect it
2263     segmentation.selectedTObj.deselect();
2264     segmentation.selectedTObj={};
2265 end
2266 if ~isempty(segmentation.selectedObj) %if exist a selected object then deselect it
2267     segmentation.selectedObj.selected=0;
2268     segmentation.selectedObj={};
2269 end
2270
2271 butonType=get(get(haxe,'parent'),'SelectionType');
2272 pt = get(haxe, 'CurrentPoint');
2273 i=round(pt(1,2));
2274 j=round(pt(1,1));
2275 uData=get(hObject,'UserData');
2276 img=uData.image;
2277 col=zeros(1,3);
2278 col(:)=img(i,j,:);
2279 if col(1)~=1||col(2)~=1||col(2)~=1
2280     xpos=uData.xpos;
2281     linesize=uData.linesize;
2282      tcells=segmentation.tcells1;
2283     nCell=find((xpos<=j)&(xpos+linesize>=j));
2284     if ~isempty(nCell)
2285         scaleFactor=uData.scaleFactor;
2286         frame=ceil(i/scaleFactor);
2287         if tcells(nCell).birthFrame<=frame
2288             set(get(haxe,'Title'),'string',{['Cell :',num2str(nCell)],['Frame :',num2str(frame)]});
2289             if isfield(uData,'hselect')
2290                 hs=uData.hselect;
2291                 set(hs,'xData',j);
2292                 set(hs,'yData',i);
2293             else
2294                 hold(haxe,'on');
2295                 uData.hselect=plot(haxe,j,i,'co','hitTest','off');
2296                 hold(haxe,'off');
2297             end
2298             set(hObject,'UserData',uData);
2299             if strcmp(butonType,'open')
2300                 %set(handles.figure1,'visible','off');
2301                 set(handles.figure1,'visible','on');
2302                 pause(0.01);
2303                 segmentation.selectedTObj=tcells(nCell);
2304                 tcells(nCell).select();
2305 %                 for i=1:length(tcells(nCell).Obj)
2306 %                     if tcells(nCell).Obj(i).image==frame;
2307 %                         segmentation.selectedObj=tcells(nCell).Obj(i);
2308 %                     end
2309 %                 end
2310                 Change_Disp1(frame,handles);
2311             end
2312         end
2313     end
2314 end;
2315
2316 % ------------------------------------------------------------------------
2317 function mouseAxesImage(hObject, eventdata, handles)
2318 % use to deselect objects
2319 global segmentation
2320
2321 butonType=get(handles.figure1,'SelectionType');
2322
2323 if ~isempty(segmentation.selectedObj)
2324     %segmentation.selectedObj.selected=false;
2325     if ishandle(segmentation.selectedObj.hcontour)
2326         set(segmentation.selectedObj.hcontour,'Marker','none');
2327         set(segmentation.selectedObj.hcontour,'Selected','off');
2328     end
2329     set(handles.edit_Cell_Properties,'string',[]);
2330     segmentation.selectedObj={};
2331
2332 end
2333
2334 if strcmp(butonType,'open')
2335     if ~isempty(segmentation.selectedTObj)
2336         segmentation.selectedTObj.deselect();
2337     end
2338
2339 set(handles.edit_TCell_Properties,'string',[]);
2340 segmentation.selectedTObj={};
2341 end
2342
2343
2344
2345 %------------------------------------------------------------------------
2346 %function to select an object with the mouse
2347 function mouseSelectObject(hObject, eventdata, handles)
2348 %used to select the objects with mouse
2349
2350 global segmentation
2351
2352 butonType=get(handles.figure1,'SelectionType');%get the tipe of click
2353
2354 %deselect selected object
2355 if ~isempty(segmentation.selectedObj) % if already selected an object
2356     %segmentation.selectedObj.selected=false;
2357     if ishandle(segmentation.selectedObj.hcontour)&&(segmentation.selectedObj.hcontour~=0)
2358         set(segmentation.selectedObj.hcontour,'Marker','none');
2359         set(segmentation.selectedObj.hcontour,'Selected','off');
2360     end
2361     segmentation.selectedObj={};
2362 end
2363
2364 %deselect selected object
2365 if ~isempty(segmentation.selectedTObj)
2366     segmentation.selectedTObj.deselect();
2367     segmentation.selectedTObj={};
2368 end
2369
2370 %change the contour
2371 set(hObject,'Selected','on');
2372 set(hObject,'Marker','*','MarkerSize',4,'MarkerEdgeColor','c');
2373
2374 %get the selected object from user data
2375 str=get(hObject,'DisplayName');
2376 segmentation.selectedObj=get(hObject,'userdata');
2377 %segmentation.selectedObj.selected=true;
2378 segmentation.selectedType=str;
2379 n=segmentation.selectedObj.n;
2380
2381 %move the object with the mouse
2382 if strcmpi(butonType,'normal') && segmentation.selectedObj.move==1 && isempty(eventdata)
2383     %if clicked , if allowed to move , if object selected by mouse , not by
2384     %change Disp1
2385     old = get(gca, 'CurrentPoint');
2386     segmentation.myHandles.oldPoint=old;
2387     set(handles.figure1, 'WindowButtonMotionFcn',{@mouse_dragginObj,hObject});
2388     segmentation.frameChanged(segmentation.frame1)=1;
2389 end
2390
2391 %lock the object by duble click
2392 if segmentation.selectedObj.move==1 &&strcmp(butonType,'open')
2393     segmentation.selectedObj.move=0;
2394 end
2395
2396
2397 %show the fields of the object in the cell properties
2398 s='';
2399 for i=1:length(segmentation.showFieldsObj)
2400     if isnumeric(segmentation.selectedObj.(segmentation.showFieldsObj{i}))
2401         sprop=segmentation.selectedObj.(segmentation.showFieldsObj{i});
2402         if size(sprop,1)>size(sprop,2)
2403             sprop=sprop';
2404         end
2405         s=[s,segmentation.showFieldsObj{i},': ',num2str(sprop),'\n'];
2406     end
2407 end
2408 s=sprintf(s);
2409 set(handles.edit_Cell_Properties,'string',s);
2410
2411
2412 %select the tobject coresponding to the object
2413 if strcmp(str,'cells1')
2414     if segmentation.cells1Mapped(segmentation.frame1)
2415         segmentation.selectedTObj=segmentation.tcells1(n);
2416     end
2417 end
2418 % if strcmp(str,'cells2')
2419 %     if segmentation.cells1Mapped(segmentation.frame1)
2420 %         segmentation.selectedTObj=segmentation.tcells2(n);
2421 %     end
2422 % end
2423 if strcmp(str,'budnecks')
2424     if segmentation.budnecksMapped(segmentation.frame1)
2425         segmentation.selectedTObj=segmentation.tbudnecks(n);
2426     end
2427 end
2428
2429
2430 %select tobject by duble click and if the pedigree is shown , show in
2431 %pedigree the coresponding cell
2432 if strcmp(butonType,'open')&&~isempty(segmentation.selectedTObj)
2433
2434     segmentation.selectedTObj.select();
2435
2436     if isfield(segmentation.myHandles,'pedigreeImage') && ishandle(segmentation.myHandles.pedigreeImage)% show the cell on the pedigree image
2437         uData=get(segmentation.myHandles.pedigreeImage,'UserData');
2438         xpos=uData.xpos;
2439         %linesize=uData.linesize;
2440         %tcells=uData.tcells;
2441         %nCell=find((xpos<=j)&(xpos+linesize>=j));
2442         %if ~isempty(nCell)
2443         scaleFactor=uData.scaleFactor;
2444         frame=segmentation.selectedObj.image;
2445         x=xpos(n);
2446         y=frame*scaleFactor;
2447         haxe=uData.haxe;
2448         if isfield(uData,'hselect')
2449             hs=uData.hselect;
2450             set(hs,'xData',x);
2451             set(hs,'yData',y);
2452         else
2453             hold(haxe,'on');
2454             uData.hselect=plot(haxe,x,y,'co','hitTest','off');
2455             hold(haxe,'off');
2456         end
2457         set(hObject,'UserData',uData);
2458
2459     end
2460 end
2461
2462 %modify the string coresponding to the tcell properties edit box
2463 if ~isempty(segmentation.selectedTObj)
2464     s='';
2465     for i=1:length(segmentation.showFieldsTObj)
2466         if strcmp(class(segmentation.selectedTObj.(segmentation.showFieldsTObj{i})),'double')
2467             s=[s,segmentation.showFieldsTObj{i},': ',num2str(segmentation.selectedTObj.(segmentation.showFieldsTObj{i})),'\n'];
2468         end
2469     end
2470     s=sprintf(s);
2471     set(handles.edit_TCell_Properties,'string',s);
2472 else
2473     set(handles.edit_TCell_Properties,'string',[]);
2474 end
2475
2476 %-----------------------------------------------------------------------
2477 %function to move objects when thei are draggd
2478 function mouse_dragginObj(hObect,evendata,obj)
2479 % real time dragging function
2480 %Mouse click + drag mouve selected object
2481
2482 global segmentation
2483 old=segmentation.myHandles.oldPoint;
2484 pt = get(gca, 'CurrentPoint');
2485 X=get(obj,'xData');
2486 Y=get(obj,'yData');
2487 set(obj, 'xData', (pt(1)-old(1))+X);
2488 set(obj, 'yData', (pt(1,2)-old(1,2))+Y);
2489 segmentation.selectedObj.x=(pt(1)-old(1))+X;
2490 segmentation.selectedObj.y=(pt(1,2)-old(1,2))+Y;
2491 select=segmentation.selectedObj;
2492 t=get(segmentation.selectedObj.htext,'position');
2493 X=t(1);
2494 Y=t(2);
2495 t(1)=(pt(1)-old(1))+X;
2496 t(2)=(pt(1,2)-old(1,2))+Y;
2497 set(select.htext, 'position', t);
2498 segmentation.selectedObj.ox=t(1);
2499 segmentation.selectedObj.oy=t(2);
2500 %set(select.htext, 'yData', (pt(1,2)-old(1,2))+Y);
2501
2502 segmentation.myHandles.oldPoint=pt;
2503
2504 %change the status text
2505 function status(str,handles)
2506 % set status
2507 set(handles.text_status,'String',str);
2508 pause(0.01);
2509
2510 % --- Executes on key press with focus on figure1 or any of its controls.
2511 function figure1_WindowKeyPressFcn(hObject, eventdata, handles)
2512
2513 %shortcut keys callback
2514 %called each time a key is presed
2515
2516 global segmentation
2517 if isfield(eventdata,'VerticalScrollCount')
2518     return
2519 end
2520 if strcmp(eventdata.Key,'leftarrow')
2521     %disp('left');
2522     pushbutton_Previous1_Callback(handles.pushbutton_Previous1, [], handles);
2523
2524 end
2525 if strcmp(eventdata.Key,'rightarrow')
2526     %disp('rightarrow');
2527     pushbutton_Next1_Callback(handles.pushbutton_Next1, [], handles);
2528 end
2529
2530 if strcmp(eventdata.Key,'delete')
2531
2532     pushbutton_Delete_Object_Callback(handles.pushbutton_Delete_Object, [], handles);
2533 end
2534
2535 %check all registred keys
2536 for i=1:size(segmentation.shorcutKeys,1)
2537     if ~isempty(segmentation.shorcutKeys{i,1})
2538         if isempty(segmentation.shorcutKeys{i,2})
2539             segmentation.shorcutKeys{i,2}=eventdata.Key;
2540         else
2541             if strcmp(segmentation.shorcutKeys{i,2},eventdata.Key)
2542                 %togle the value of the function
2543                 set(handles.(segmentation.shorcutKeys{i,1}),'value',not(get(handles.(segmentation.shorcutKeys{i,1}),'value')));
2544                 feval(get(handles.(segmentation.shorcutKeys{i,1}),'Callback'),handles.(segmentation.shorcutKeys{i,1}),[]);
2545             end
2546         end
2547     end
2548 end
2549 status('Idle',handles);
2550
2551 % --- Executes on mouse press over figure background, over a disabled or
2552 % --- inactive control, or over an axes background.
2553 function figure1_WindowButtonUpFcn(hObject, eventdata, handles)
2554 set(handles.figure1, 'WindowButtonMotionFcn','');
2555
2556
2557
2558 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2559 %%%%%%%%%%%%%%%%%%%%%%%%% CONTEXT MENUS CALLBACK %%%%%%%%%%%%%%%%%%%%%%%%%
2560 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2561
2562 %===================== BUTTONS CONTEXT MENU ==============================
2563
2564 % --------------------------------------------------------------------
2565 function Set_Key_Callback(hObject, eventdata, handles)
2566 %right click on the button to set the key
2567
2568 global segmentation
2569
2570 %verify the tolbar buttons (the key function does not work while buttons are pressed)
2571 %--------------------------------------------------------------------
2572 str=get(handles.uitoggletool1,'state');
2573 if strcmpi(str,'on')
2574     status('set "Zoom in" button off before',handles);
2575     return
2576 end
2577 str=get(handles.uitoggletool2,'state');
2578 if strcmpi(str,'on')
2579     status('set "Zoom Out" button off before',handles);
2580     return
2581 end
2582 str=get(handles.uitoggletool3,'state');
2583 if strcmpi(str,'on')
2584     status('set "Pan" button off before',handles);
2585     return
2586 end
2587 str=get(handles.uitoggletool4,'state');
2588 if strcmpi(str,'on')
2589     status('set "Data Cursor" button off before',handles);
2590     return
2591 end
2592 %------------------------------------------------------------------
2593
2594 status(['Set Key for ',get(gco,'tag')],handles);
2595 val=false;
2596 for i=1:size(segmentation.shorcutKeys,1)
2597     if strcmp(segmentation.shorcutKeys{i,1},get(gco,'tag'))
2598         segmentation.shorcutKeys{i,2}={};
2599         val=true;
2600     end
2601 end
2602 if ~val
2603 segmentation.shorcutKeys{end+1,1}=get(gco,'tag');
2604 end
2605
2606 %===================== OBJECTS CONTEXT MENU ==============================
2607
2608 % --------------------------------------------------------------------
2609 function Context_Objects_Edit_Contour_Callback(hObject, eventdata, handles)
2610 pushbutton_Edit_Contour_Callback(handles.pushbutton_Edit_Contour, eventdata, handles)
2611
2612 % --------------------------------------------------------------------
2613 function Context_Objects_Callback(hObject, eventdata, handles)
2614
2615 % --------------------------------------------------------------------
2616 function Context_Objects_Set_Number_Callback(hObject, eventdata, handles)
2617 pushbutton_Set_Number_Callback(handles.pushbutton_Set_Number, [], handles)
2618
2619 % --------------------------------------------------------------------
2620 function Context_Objects_Delete_Callback(hObject, eventdata, handles)
2621 pushbutton_Delete_Object_Callback(handles.pushbutton_Delete_Object, [], handles);
2622
2623 % --------------------------------------------------------------------
2624 function Context_Objects_Copy_Callback(hObject, eventdata, handles)
2625 global segmentation;
2626 selObj=get(gco,'userdata');
2627 segmentation.copyedObj=selObj;
2628 segmentation.copyedType=segmentation.selectedType;
2629
2630 % --------------------------------------------------------------------
2631 function Context_Objects_Move_Callback(hObject, eventdata, handles)
2632 selObj=get(gco,'userdata'); %get object from userdata of graphic object
2633 selObj.move=1;
2634
2635 % --------------------------------------------------------------------
2636 function Context_Objects_Lock_Callback(hObject, eventdata, handles)
2637
2638 selObj=get(gco,'userdata'); %get object from userdata of graphic object
2639 selObj.move=0;
2640
2641 % --------------------------------------------------------------------
2642 function Context_Objects_Set_Mother_Callback(hObject, eventdata, handles)
2643 pushbutton_Set_Mother_Callback(handles.pushbutton_Set_Mother, [], handles)
2644
2645 % --------------------------------------------------------------------
2646 function Context_Objects_Copy_Next_Frame_Callback(hObject, eventdata, handles)
2647 global segmentation;
2648 selObj=get(gco,'userdata');
2649 segmentation.copyedObj=selObj;
2650 segmentation.copyedType=segmentation.selectedType;
2651 segmentation.frame1=segmentation.frame1+1;
2652 Context_Image_Paste_Callback(handles.Context_Image_Paste, [], handles)
2653 segmentation.frameChanged(segmentation.frame1+1)=1;
2654
2655
2656 %===================== IMAGE CONTEXT MENU ==============================
2657 %(right click on the image)
2658 % --------------------------------------------------------------------
2659 function Context_Image_Paste_Callback(hObject, eventdata, handles)
2660 %paste the object to the image
2661 global segmentation;
2662 if ~isempty(segmentation.copyedObj)
2663     obj= segmentation.(segmentation.copyedType);
2664     if size(obj,1)>=segmentation.frame1
2665         added=false;
2666         for i=1:length(obj(segmentation.frame1,:))
2667             if obj(segmentation.frame1,i).ox==0
2668
2669                 added=true;
2670                 break;
2671             end
2672         end
2673         if ~added
2674             i=length(obj(segmentation.frame1,:))+1;
2675         end
2676     else i=1;
2677     end
2678     obj(segmentation.frame1,i)=phy_Object;
2679     names = fieldnames(segmentation.copyedObj);
2680     for j=1:length(names)
2681         obj(segmentation.frame1,i).(names{j})=segmentation.copyedObj.(names{j});
2682     end;
2683     obj(segmentation.frame1,i).move=1;
2684     obj(segmentation.frame1,i).image=segmentation.frame1;
2685     obj(segmentation.frame1,i).selected=0;
2686     segmentation.([segmentation.copyedType,'Segmented'])(segmentation.frame1)=1;
2687     segmentation.frameChanged(segmentation.frame1)=1;
2688     segmentation.(segmentation.copyedType)=obj;
2689     Change_Disp1('refresh',handles);
2690
2691 end
2692
2693 % --------------------------------------------------------------------
2694 function Context_Image_Callback(hObject, eventdata, handles)
2695
2696 % --------------------------------------------------------------------
2697 function Context_Image_Paste_Images_Callback(hObject, eventdata, handles)
2698 % hObject    handle to Context_Image_Paste_Images (see GCBO)
2699 % eventdata  reserved - to be defined in a future version of MATLAB
2700 % handles    structure with handles and user data (see GUIDATA)
2701
2702 global segmentation
2703 global timeLapse
2704 %---------------------
2705 %dialog box
2706 prompt = {'Enter first frame:','Enter last frame:'};
2707 dlg_title = 'Add object to frames';
2708 num_lines = 1;
2709 def = {num2str(segmentation.frame1),num2str(timeLapse.numberOfFrames)};
2710 %def = {num2str(bSeg(1)),num2str(bSeg(end))};
2711 answer = inputdlg(prompt,dlg_title,num_lines,def);
2712 if isempty(answer)
2713     return
2714 end
2715 startFrame=str2double(answer(1));
2716 endFrame=str2double(answer(2));
2717 %-----------------------
2718 if ~isempty(segmentation.copyedObj)
2719     obj= segmentation.(segmentation.copyedType);
2720     for frame1=startFrame:endFrame
2721
2722         if size(obj,1)>=frame1
2723             added=false;
2724             for i=1:length(obj(frame1,:))
2725                 if obj(frame1,i).ox==0
2726
2727                     added=true;
2728                     break;
2729                 end
2730             end
2731             if ~added
2732                 i=length(obj(frame1,:))+1;
2733             end
2734         else i=1;
2735         end
2736         obj(frame1,i)=phy_Object;
2737         names = fieldnames(segmentation.copyedObj);
2738         for j=1:length(names)
2739             obj(frame1,i).(names{j})=segmentation.copyedObj.(names{j});
2740         end;
2741         obj(frame1,i).move=1;
2742         obj(frame1,i).image=frame1;
2743         obj(frame1,i).selected=0;
2744
2745         segmentation.([segmentation.copyedType,'Segmented'])(frame1)=1;
2746         segmentation.frameChanged(frame1)=1;
2747
2748
2749     end
2750     segmentation.(segmentation.copyedType)=obj;
2751     Change_Disp1('refresh',handles);
2752 end
2753
2754
2755 % --------------------------------------------------------------------
2756 function Check_Setings_Callback(hObject, eventdata, handles)
2757 global segmentation
2758
2759 %check struct saved from previous versions
2760 if ~isfield(segmentation,'check')
2761     segmentation.check.budneckTimeLow=5;
2762     segmentation.check.budneckTimeHigh=20;
2763 end
2764
2765 %-------------------------------------------------------------------------
2766 %dialog
2767 prompt = {'Enter lowest budneck allert time:','Enter highest budneck allert time:'};
2768 dlg_title = 'Check parametres';
2769 num_lines = 1;
2770 def = {num2str(segmentation.check.budneckTimeLow),num2str(segmentation.check.budneckTimeHigh)};
2771 answer = inputdlg(prompt,dlg_title,num_lines,def);
2772 if isempty(answer)
2773     return
2774 end
2775 %------------------------------------------------------------------------
2776
2777 segmentation.check.budneckTimeLow=str2double(answer(1));
2778 segmentation.check.budneckTimeHigh=str2double(answer(2));
2779
2780
2781 % --- Executes on button press in checkbox_Use_Display_Image.
2782 function checkbox_Use_Display_Image_Callback(hObject, eventdata, handles)
2783 Change_Disp1('refresh',handles);
2784
2785
2786 % --- Executes on button press in checkbox_Use_Cropped_Image.
2787 function checkbox_Use_Cropped_Image_Callback(hObject, eventdata, handles)
2788 Change_Disp1('refresh',handles);
2789
2790
2791 % --------------------------------------------------------------------
2792 function Analyse_Callback(hObject, eventdata, handles)
2793 % hObject    handle to Analyse (see GCBO)
2794 % eventdata  reserved - to be defined in a future version of MATLAB
2795 % handles    structure with handles and user data (see GUIDATA)
2796
2797
2798 % --------------------------------------------------------------------
2799 function Analyse_Levels_Inside_Contours_Callback(hObject, eventdata, handles)
2800
2801 global segmentation;
2802
2803
2804 %dialog
2805 %-------------------------------------------------------------------------
2806 prompt = {'Chose the object to be analysed: (cells1/budnecks)','Enter analyse channel'};
2807 dlg_title = 'Analyse fluorescence inside contours';
2808 num_lines = 1;
2809 def = {'cells1','1'};
2810 answer = inputdlg(prompt,dlg_title,num_lines,def);
2811 if isempty(answer)
2812     return
2813 end
2814 %------------------------------------------------------------------------
2815 a1=answer{1};
2816 a2=str2double(answer{2});
2817
2818 segmentedFrames=find(segmentation.([a1,'Segmented']));%all segemented frames
2819 obj=segmentation.(a1); %chosen object
2820
2821 status('Analyse Fluorescence',handles);
2822
2823 c=0;
2824 phy_progressbar;
2825 %for all segmented images do the analyse
2826 for i=segmentedFrames
2827     c=c+1;
2828     phy_progressbar(c/length(segmentedFrames));
2829
2830     %read and scale the fluorescence image
2831     img=phy_loadTimeLapseImage(segmentation.position,i,a2,'non retreat');
2832     img=imresize(img,segmentation.sizeImageMax);
2833
2834     %create masks and mean the pixels
2835     for j=1:length(obj(i,:))
2836         if obj(i,j).n~=0 && ~isempty(obj(i,j).x)
2837             mask = poly2mask(obj(i,j).x,obj(i,j).y,segmentation.sizeImageMax(1),segmentation.sizeImageMax(2));
2838             obj(i,j).meanLevelsInside=mean(img(mask));
2839         end
2840     end
2841 end
2842 status('Idle',handles);
2843
2844
2845
2846 % --------------------------------------------------------------------
2847 function Analyse_Plot_Levels_Callback(hObject, eventdata, handles)
2848
2849 global segmentation;
2850
2851 %dialog
2852 %-------------------------------------------------------------------------
2853 prompt = {'Chose the object to be ploted: (cells1/budnecks)'};
2854 dlg_title = 'Plot fluorescence inside contours';
2855 num_lines = 1;
2856 def = {'cells1'};
2857 answer = inputdlg(prompt,dlg_title,num_lines,def);
2858 if isempty(answer)
2859     return
2860 end
2861 %------------------------------------------------------------------------
2862 a1=answer{1};
2863 tobj=segmentation.(['t',a1]); %chosen object
2864
2865 ploted=[];
2866 h=[];
2867 hf=figure;
2868 ha=axes;
2869 couleurs = hsv(length(tobj));
2870 for i=1:length(tobj)
2871     if tobj(i).N~=0
2872         ploted=[ploted i];
2873         values=[];
2874         frames=[];
2875         for j=1:length(tobj(i).Obj)
2876             values=[values,tobj(i).Obj(j).meanLevelsInside];
2877             frames=[frames,tobj(i).Obj(j).image];
2878         end
2879         [frames,IX]=sort(frames);
2880         values(:)=values(IX);
2881         h(i)=line(frames,values,'color',couleurs(i,:));
2882         set(h(i),'ButtonDownFcn',{@mouseFluoPlot,ha});
2883         set(h(i),'DisplayName',num2str(i),'SelectionHighlight','off');
2884         %legend('toggle');
2885     end
2886     %legend('show');
2887 end
2888
2889 function mouseFluoPlot(hObject, eventdata, ha)
2890 %deselect
2891 set(get(ha,'Children'),'selected','off','LineWidth',0.5,'Marker','none');
2892 %select mouse click
2893 set(hObject,'LineWidth',2,'Marker','o','MarkerEdgeColor','c','MarkerSize',3,'Selected','on');
2894 title(ha,['object ',get(hObject,'DisplayName')]);